### DISCUSSION TITLE
Can I run Hoppscotch behind Reverse Proxy using Traefik with PathPrefix ( like www.example.com/hoppscotch )

### DISCUSSION THREAD

**Discussion by Kaemaros** [hoppscotch/hoppscotch#3172] [Q&A]
Can I run Hoppscotch behind Reverse Proxy using Traefik with PathPrefix ( like www.example.com/hoppscotch )

I use docker-compose file from hoppsoctch with addtional line
```
hoppscotch-app:
    container_name: hoppscotch-app
    build:
      dockerfile: packages/hoppscotch-selfhost-web/Dockerfile
      context: .
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3000:8080"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.hoppscotch.entrypoints=websecure'
      - 'traefik.http.routers.hoppscotch.tls=true'
      - 'traefik.http.routers.hoppscotch.rule=Host(`${HOST_URL}`) && PathPrefix(`/hoppscotch`)'
      - 'traefik.http.routers.hoppscotch.middlewares=hoppscotch-stripprefix'
      - 'traefik.http.middlewares.hoppscotch-stripprefix.stripprefix.prefixes=/hoppscotch'
      - 'traefik.http.services.hoppscotch.loadBalancer.server.port=8080'
```
but it turn out to be white blank page
