### DISCUSSION TITLE
Working example using docker compose and Traefik (reverse proxy)

### DISCUSSION THREAD

**Discussion by drilus** [hoppscotch/hoppscotch#3443] [General]
I wanted to save everyone the same headaches I went through. The example documentation is decent, but not very clear.

You'll need to have Traefik already configured for this work.

`docker-compose.yml`
```yml
version: '2'

services:
  hoppscotch-aio:
    container_name: hoppscotch-aio
    image: 'hoppscotch/hoppscotch:2023.8.1'
    networks:
      - proxy
    volumes:
      - pw_backend:/usr/src/app/node_modules/
    labels:
      # Create http to https middleware
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.hoppscotch-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.hoppscotch-redirect.redirectscheme.permanent=true'
      # cors middleware
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Content-Type, Authorization, X-Requested-With'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true'
      - 'traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://hoppscotch.mydomain.com,https://admin-hoppscotch.mydomain.com'
      - 'traefik.http.middlewares.cors.headers.accesscontrolmaxage=100'
      - 'traefik.http.middlewares.cors.headers.addvaryheader=true'
      # front-end http route
      - 'traefik.http.routers.hoppscotch.middlewares=hoppscotch-redirect'
      - 'traefik.http.routers.hoppscotch.rule=Host(`hoppscotch.mydomain.com`)'
      - 'traefik.http.routers.hoppscotch.entrypoints=web'
      - 'traefik.http.routers.hoppscotch.service=hoppscotch'
      - 'traefik.http.services.hoppscotch.loadbalancer.server.port=3000'
      # front-end https route
      - 'traefik.http.routers.hoppscotch-secure.rule=Host(`hoppscotch.mydomain.com`)'
      - 'traefik.http.routers.hoppscotch-secure.entrypoints=websecure'
      - 'traefik.http.routers.hoppscotch-secure.tls=true'
      - 'traefik.http.routers.hoppscotch-secure.middlewares=cors'
      - 'traefik.http.services.hoppscotch-secure.loadbalancer.server.port=3000'
      - 'traefik.http.routers.hoppscotch-secure.service=hoppscotch-secure'
      # admin dashboard https route
      - 'traefik.http.routers.hoppscotch-admin.rule=Host(`admin-hoppscotch.mydomain.com`)'
      - 'traefik.http.services.hoppscotch-admin.loadbalancer.server.port=3100'
      - 'traefik.http.routers.hoppscotch-admin.entrypoints=websecure'
      - 'traefik.http.routers.hoppscotch-admin.tls=true'
      - 'traefik.http.routers.hoppscotch-admin.service=hoppscotch-admin'
      - 'traefik.http.routers.hoppscotch-admin.middlewares=cors'
      # back-end https route
      - 'traefik.http.routers.hoppscotch-api.rule=Host(`api-hoppscotch.mydomain.com`)'
      - 'traefik.http.services.hoppscotch-api.loadbalancer.server.port=3170'
      - 'traefik.http.routers.hoppscotch-api.entrypoints=websecure'
      - 'traefik.http.routers.hoppscotch-api.tls=true'
      - 'traefik.http.routers.hoppscotch-api.service=hoppscotch-api'
      - 'traefik.http.routers.hoppscotch-api.middlewares=cors'
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - 3000:3000
      - 3100:3100
      - 3170:3170

  hoppscotch-db:
    image: postgres:15
    ports:
      - 5432:5432
    networks:
      - proxy
    volumes:
      - pw_postgres_data:/var/lib/postgresql/data
    #user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cretpa$$word
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pw_postgres_data:
      driver: local
  pw_backend:
      driver: local

networks:
  proxy:
    external: true
```

`.env`
```ini
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:s3cretpa$$word@hoppscotch-db:5432/hoppscotch?connect_timeout=300

# Auth Tokens Config
JWT_SECRET=secret1233
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY= 3
REFRESH_TOKEN_VALIDITY=604800000 # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY=86400000 # Default validity is 1 day (86400000 ms) in ms
SESSION_SECRET=fsdjkfluewior97987fdks.jaksdfjasfsdfsdyui

# Hoppscotch App Domain Config
REDIRECT_URL=https://hoppscotch.mydomain.com
WHITELISTED_ORIGINS=https://api-hoppscotch.mydomain.com,https://hoppscotch.mydomain.com,https://admin-hoppscotch.mydomain.com
VITE_ALLOWED_AUTH_PROVIDERS=GOOGLE,GITHUB,MICROSOFT,EMAIL

# Google Auth Config
GOOGLE_CLIENT_ID=************************************************
GOOGLE_CLIENT_SECRET=************************************************
GOOGLE_CALLBACK_URL=https://api-hoppscotch/v1/auth/google/callback
GOOGLE_SCOPE=email,profile

# Github Auth Config
GITHUB_CLIENT_ID=************************************************
GITHUB_CLIENT_SECRET=************************************************
GITHUB_CALLBACK_URL=https://api-hoppscotch/v1/auth/github/callback
GITHUB_SCOPE=user:email

# Microsoft Auth Config
MICROSOFT_CLIENT_ID=************************************************
MICROSOFT_CLIENT_SECRET=************************************************
MICROSOFT_CALLBACK_URL=https://api-hoppscotch/v1/auth/microsoft/callback
MICROSOFT_SCOPE=user.read
MICROSOFT_TENANT=common

# Mailer config
MAILER_SMTP_URL="smtp://username:password@smtp.host.net:587"
MAILER_ADDRESS_FROM=no-replies@mydomain.com

# Rate Limit Config
RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP


#-----------------------Frontend Config------------------------------#


# Base URLs
VITE_BASE_URL=https://hoppscotch.mydomain.com
VITE_SHORTCODE_BASE_URL=https://hoppscotch.mydomain.com
VITE_ADMIN_URL=https://admin-hoppscotch.mydomain.com

# Backend URLs
VITE_BACKEND_GQL_URL=https://api-hoppscotch.mydomain.com/graphql
VITE_BACKEND_WS_URL=wss://api-hoppscotch.mydomain.com/graphql
VITE_BACKEND_API_URL=https://api-hoppscotch.mydomain.com/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy
```

I'm not sure if the http verbs: PATCH or DELETE are needed. If so, simply add them to the accesscontrolallowmethods in the cors middleware.

Common problems I've noticed in the issues section:

- The AIO uses specific ports defined for Front-End, Back-End, and Admin. There's a few issues where a proxy was set up that used the same domain for the front-end and back-end. This causes confusion as the proxy will attempt to route to the same port.
- A bunch of cors issues...mostly involving not adding the required configs to the proxy
- Incorrect .env variables...solve by removing the quotes around the values

Feel free to add to/correct/comment.
