### DISCUSSION TITLE
Issue: Admin Panel Fails to Connect to Backend

### DISCUSSION THREAD

**Discussion by vrathore18** [hoppscotch/hoppscotch#5016] [Q&A]
Configuration:

```
urls:
  base: "http://hoppscotch.stage.foo.com"
  shortcode: "http://hoppscotch.stage.foo.com"
  admin: "http://hoppscotch.stage.foo.com"
  backend:
    gql: "http://hoppscotch.stage.foo.com/graphql"
    ws: "ws://hoppscotch.stage.foo.com/graphql"
    api: "http://hoppscotch.stage.foo.com/v1"
  redirect: "http://hoppscotch.stage.foo.com"
  whitelistedOrigins: "http://hoppscotch.stage.foo.com/backend,http://hoppscotch.stage.foo.com,http://hoppscotch.stage.foo.com/admin"

community:
  enableSubpathBasedAccess: true

```
**Issue**:

I can access the app at: http://hoppscotch.stage.foo.com
Backend works correctly at: http://hoppscotch.stage.foo.com/backend
But, when I try to access the admin panel at:
http://hoppscotch.stage.foo.com/admin

I get the error:
<img width="1432" alt="Screenshot 2025-04-23 at 11 55 36 AM" src="https://github.com/user-attachments/assets/658c95f6-832e-4f9a-b722-ed429d54f6c9" />
<img width="1439" alt="Screenshot 2025-04-23 at 11 55 59 AM" src="https://github.com/user-attachments/assets/a56ca75f-2ed2-4c9a-8769-b630c715c536" />
<img width="1438" alt="Screenshot 2025-04-23 at 11 56 12 AM" src="https://github.com/user-attachments/assets/38540130-9c18-4a1f-aafb-25251e596d8d" />

Failed to connect to the backend server, make sure the backend is setup correctly.
