### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by hibare** [hoppscotch/hoppscotch#1243]
**Describe the bug**
Nothing loads in UI, continues to show loading cirlces

**To Reproduce**
Run followin docker-compose snippet

```
version: "3.7"

services:
  postwoman:
    container_name: postwoman
    image: liyasthomas/postwoman
    hostname: postwoman
    environment:
      TZ: "Asia/Kolkata"
    ports:
      - 8000:8000
    restart: unless-stopped
```

**Expected behavior**
Page will load

**Screenshots**
![Screenshot from 2020-10-06 18-47-35](https://user-images.githubusercontent.com/20609766/95206603-85a4e600-0804-11eb-850f-60c5934c3b92.png)

**Desktop (please complete the following information):**
 - OS: Elementary Os
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Version: 80.0.1

**Additional context**
Error in Browser console.
TypeError: Lo is undefined
