### ISSUE TITLE
[feature]: add docker images to dockerhub

### ISSUE THREAD

**Issue by gaozhidf** [hoppscotch/hoppscotch#3069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

can u add docker images to dockerhub, and we can setup the backend services quickly.
something like https://github.com/gaozhidf/hoppscotch-docker-compose/tree/main

### Why should this be worked on?

newman can setup the backend services quickly

**Comment by webysther** [comment]
yeah, will be incredable, maybe using the lsio model, works well, fast to deploy and have the best boilerplate structure for keep up and running, [just check out](https://docs.linuxserver.io/general/running-our-containers#base-images) [ref](https://www.linuxserver.io/#standardised-images) @liyasthomas, maybe ask for help to the guys!

**Comment by webysther** [comment]
As a suggestion, in getting started, just put this in the first for docker:

```sh
version: '3.9'

services:
  hoppscotch:
    image: hoppscotch/hoppscotch
    container_name: app-hoppscotch
    networks:
      hoppscotch:
    ports:
      - 3000:3000

networks:
  hoppscotch:
    name: hoppscotch
```

Fast to start the hands-on, i got this [from this video](https://www.youtube.com/watch?v=l2DWcWb9HlM)

**Comment by webysther** [comment]
Send all requests to same container just changing the port and support sqlite, this will help so many devs around, my suggestion:

```yaml
version: '3.9'

services:
  hoppscotch:
    image: hoppscotch/hoppscotch
    container_name: app-hoppscotch
    networks:
      hoppscotch:
    # stack is used on portainer
    env_file: stack.env
    volumes:
      # along with backend add sqlite
      - /home/docker/hoppscotch:/data 
    ports:
      - 3000:3000 # frontent
      - 3001:3001 # backend
      - 3100:3100 # admin

networks:
  hoppscotch:
    name: hoppscotch
```

Its perfect to have all services decoupled, but for self-hosted the deploy-time/maintenance is the key.
