### ISSUE TITLE
[bug]: table `public.User` does not exist in the current database

### ISSUE THREAD

**Issue by dreamwhite** [hoppscotch/hoppscotch#3203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try logging using GitHub (after editing `.env` file properly), I see in the docker console this error:

```
hoppscotch-hoppscotch-db-1  | 2023-07-20 22:26:20.333 UTC [38] STATEMENT:  INSERT INTO "public"."User" ("uid","displayName","email","photoURL","isAdmin","createdOn") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."User"."uid"
hoppscotch-backend          | [Nest] 19  - 07/20/2023, 10:26:20 PM   ERROR [ExceptionsHandler]
hoppscotch-backend          | Invalid `this.prisma.user.create()` invocation in
hoppscotch-backend          | /usr/src/app/dist/user/user.service.js:104:52
hoppscotch-backend          |
hoppscotch-backend          |   101 async createUserSSO(accessTokenSSO, refreshTokenSSO, profile) {
hoppscotch-backend          |   102     const userDisplayName = !profile.displayName ? null : profile.displayName;
hoppscotch-backend          |   103     const userPhotoURL = !profile.photos ? null : profile.photos[0].value;
hoppscotch-backend          | → 104     const createdUser = await this.prisma.user.create(
hoppscotch-backend          | The table `public.User` does not exist in the current database.
hoppscotch-backend          | Error:
hoppscotch-backend          | Invalid `this.prisma.user.create()` invocation in
hoppscotch-backend          | /usr/src/app/dist/user/user.service.js:104:52
hoppscotch-backend          |
hoppscotch-backend          |   101 async createUserSSO(accessTokenSSO, refreshTokenSSO, profile) {
hoppscotch-backend          |   102     const userDisplayName = !profile.displayName ? null : profile.displayName;
hoppscotch-backend          |   103     const userPhotoURL = !profile.photos ? null : profile.photos[0].value;
hoppscotch-backend          | → 104     const createdUser = await this.prisma.user.create(
hoppscotch-backend          | The table `public.User` does not exist in the current database.
hoppscotch-backend          |     at RequestHandler.handleRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:35024:13)
hoppscotch-backend          |     at RequestHandler.handleAndLogRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34996:12)
hoppscotch-backend          |     at RequestHandler.request (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:34991:12)
hoppscotch-backend          |     at async PrismaService._request (/usr/src/app/node_modules/.pnpm/@prisma+client@4.8.1_prisma@4.8.1/node_modules/@prisma/client/runtime/index.js:36082:16)
hoppscotch-backend          |     at async UserService.createUserSSO (/usr/src/app/dist/user/user.service.js:104:29)
hoppscotch-backend          |     at async GithubStrategy.validate (/usr/src/app/dist/auth/strategies/github.strategy.js:35:33)
```

### Steps to reproduce

1. Go to Hoppscotch self-hosted instance (`192.168.1.23:3000` for instance)
2. Click on login, select GitHub
3. Proceed by connecting my GitHub account
4. Error in the console appears

### Environment

Production

### Version

Self-hosted

**Comment by dreamwhite** [comment]
I wanna point out also, that for whatever reason, once I click on `Login with GitHub` the browser redirects me on `localhost:3170/auth/github/callback` despite `.env` says `192.168.1.23`

**Comment by AndrewBastin** [comment]
@dreamwhite have you ran the migrations as specified on the Self-Hosted documentation ?

See: https://docs.hoppscotch.io/documentation/self-host/install-and-build#installing-dependencies

**Comment by dreamwhite** [comment]
Good morning, yes I did. I wanna remind that I'm using a docker setup so essentially the steps I did were:

- `git clone repo`
- edit `.env.example` and save it as `.env`
- `docker compose build`
- `docker-compose up hoppscotch-db`
- migrate using `docker exec -it hoppscotch-db bash` and `pnpm exec prisma migrate deploy`
- run `docker compose up`

**Comment by dreamwhite** [comment]
Regarding the login issue, these are the steps I'm following:

- visit `http://192.168.1.23:3100` (admin page)
- click on `Continue with GitHub`
- authorize the application
- I should login, but rather I'm redirected to `http://192.168.1.23:3000` where my Hoppscotch instance is available

Same happens if I visit `http://192.168.1.23:3000`. Both of them lead to the same result, namely cannot login:

![image](https://github.com/hoppscotch/hoppscotch/assets/17933708/7d885210-6823-4249-80d5-d833d89c810e)


Click on GitHub and automatically get redirected to the homepage: 

![image](https://github.com/hoppscotch/hoppscotch/assets/17933708/1946eac1-f886-4f03-b317-b49343c66174)

**Comment by balub** [comment]
@dreamwhite We use HTTP secure cookies for auth, could you try it over `https`?

**Comment by balub** [comment]
#3060

**Comment by dreamwhite** [comment]
Hi, thanks for the reply. Well, I'm self-hosting my hoppscotch instance on my ODROID N2+ at home. Will this still work?
Also please note that the building using docker is really slow on such hardware, mainly due to `node_modules` directory not being shared across the containers. Can this be fixed?

**Comment by webysther** [comment]
The build process is not a required step to deploy, only for this project because don't support dinamic .env vars to be passed after build is made, but this image skip build process after the first time: https://hub.docker.com/r/webysther/hoppscotch

**Comment by balub** [comment]
@dreamwhite it seems that you have not run the migration to populate the database with tables. You can follow [this](https://docs.hoppscotch.io/documentation/self-host/install-and-build/#installing-dependencies) to fix the issue you have.

**Comment by dreamwhite** [comment]
> The build process is not a required step to deploy, only for this project because don't support dinamic .env vars to be passed after build is made, but this image skip build process after the first time: https://hub.docker.com/r/webysther/hoppscotch

Ohhh alright! I'll let you know since I'm experiencing a weird thing with the building process, where the machine hangs probably due to resources allocation...

**Comment by AndrewBastin** [comment]
@dreamwhite closing this issue as the opened objective is fixed. We are refined the build steps in the 2023.8.0 release, please go to [Hoppscotch Docs](https://docs.hoppscotch.io/) to learn about that.

**Comment by dreamwhite** [comment]
Good evening @AndrewBastin. It seems that on a ODROID N2+ (6 core with 4GBs of RAM) the build process makes the server hang and the only possible way is rebooting it. Is there any workaround like building the app elsewhere (e.g. on my laptop) and then copying it on the server?

**Comment by AndrewBastin** [comment]
@dreamwhite we now provide prebuilt containers in Docker Hub. See: https://hub.docker.com/r/hoppscotch/hoppscotch

**Comment by dreamwhite** [comment]
Good morning @AndrewBastin. Thank you so much! It works flawlessly even when using Traefik as reverse proxy.

Attaching my `docker-compose.yml` file in case anyone wants to use the same setup:

```yaml
version: '3.8'
services:
  hoppscotch:
    image: hoppscotch/hoppscotch
    env_file:
      - .env
    depends_on:
      hoppscotch-db:
        condition: service_started
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.hoppscotch.rule=Host(`hoppscotch.my_domain.ltd`)
      - traefik.port=3000
      - traefik.http.routers.hoppscotch.tls=true
      - traefik.http.routers.hoppscotch.tls.certresolver=lets-encrypt
    networks:
      - web
      - internal

  hoppscotch-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass # <---- Change this
      POSTGRES_DB: hoppscotch # <---- Change this
      POSTGRES_HOST_AUTH_METHOD: trust  # <---- Kinda unsure about this one. Theoretically speaking of, POSTGRES_PASSWORD shouldn't be needed when using trust method. Need to change it one day
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false
```
