### ISSUE TITLE
[bug]: Error: test: does not get device identifier Login.vue:266

### ISSUE THREAD

**Issue by Overbuiltx** [hoppscotch/hoppscotch#3326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I run hoppscotch (aio + postgres) via prebuilt docker images.

The container stack is restricted with an outbound corporate firewall and is accessable by a httpd reverse proxy.
I did modify the aio Caddyfile, so one port exposes all the services - like so:

```
:80 {
        handle_path /api/* {
                reverse_proxy localhost:3170
        }

        redir /admin /admin/
        handle /admin/* {
                try_files {path} /
                root * /site/sh-admin
                file_server
        }

        handle {
                try_files {path} /
                root * /site/selfhost-web
                file_server
        }

        log {
                output stdout
                level ERROR
        }
}
```

(I also tried the built in Caddyfile, same result)

Hoppscotch loads without errors, except for /admin, which gives me a 404.

If I login via Email I get the following error in the web console:

![image](https://github.com/hoppscotch/hoppscotch/assets/144319516/4fa81f28-129f-4d07-a90d-22053670fcf9)

```
VITE_ADMIN_URL=https://hoppscotch.<company>/admin
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL
# Mailer config
MAILER_SMTP_URL=smtps://hoppscotch@<company>:<pass>@smtp.<company>
MAILER_ADDRESS_FROM='"Hoppscotch" <hoppscotch@<company>>'
```

```
version: "3.7"

services:
  hoppscotch-aio:
    build: ./app
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "80:80"

  hoppscotch-db:
    image: postgres:15-alpine
    user: postgres
    environment:
      # The default user defined by the docker image
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hoppscotch
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  default:
    name: hoppscotch

```

```
FROM hoppscotch/hoppscotch:2023.8.0

COPY Caddyfile /etc/caddy/Caddyfile

ENTRYPOINT [ "tini", "--" ]
HEALTHCHECK --interval=2s CMD /bin/sh ./healthcheck.sh
CMD ["node" "/usr/src/app/aio_run.mjs"]
EXPOSE 80
```

### Steps to reproduce

1. docker-compose build
2. docker-compose up -d
3. try to login via email on website
4. Login.vue error

### Environment

Production

### Version

Self-hosted
