### ISSUE TITLE
[bug]: Collections view does not refresh after creating a collection or adding a new request

### ISSUE THREAD

**Issue by lovaszvencel** [hoppscotch/hoppscotch#3331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I switch the workspace from my workspace to any other team workspace the collection view top refreshing it after adding items into it.

For example, if I create a new collection and save it it does not appear in the list (list remains empty). I expect to see the newly created collection in the list (as works in my workspace). After I refresh the page the newly created collection appears on the list. 
Other example, if I create a new request and save it it does not appear in the list (list contains the collection only). I expect to see the newly created request in the list (as works in my workspace). After I refresh the page the newly created request appears on the list. 

### Steps to reproduce

1. Create a new team
2. Create a new collection
3. Save the dialog
Actual result: Collection list is empty
Expected result: Newly created collection is appear

### Environment

Production

### Version

Self-hosted

**Comment by frnk01** [comment]
Same for me. Need to refresh manually after performing actions. Self hosted.

**Comment by james-exp** [comment]
Same here. Occurs in case of team workspace. Self hosted too.

**Comment by JamesSFL** [comment]
Same here. Occurs in case of team workspace. Self hosted too.

**Comment by KatyaGolyagina** [comment]
Same on https://hoppscotch.io/ not only Self hosted.
We're really looking forward to the fix! 😔🙏

**Comment by buderjoh** [comment]
I think this might be a configuration issue?

https://github.com/hoppscotch/hoppscotch/issues/3587#issuecomment-1845447776

If its running under https -> VITE_BACKEND_WS_URL=**wss**://localhost:3170/graphql works for me
and i think it would work the other way around for http -> VITE_BACKEND_WS_URL=**ws**://localhost:3170/graphql

Nevertheless if you do it with your local workspace there is still this issue: https://github.com/hoppscotch/hoppscotch/issues/3208

**Comment by KatyaGolyagina** [comment]
> I think this might be a configuration issue?
> 
> [#3587 (comment)](https://github.com/hoppscotch/hoppscotch/issues/3587#issuecomment-1845447776)
> 
> If its running under https -> VITE_BACKEND_WS_URL=**wss**://localhost:3170/graphql works for me and i think it would work the other way around for http -> VITE_BACKEND_WS_URL=**ws**://localhost:3170/graphql
> 
> Nevertheless if you do it with your local workspace there is still this issue: #3208

doesn't work

**Comment by AlirezaAbsolution** [comment]
Hi,  i have same problem. I use hoppscotch as reverse proxy for mine. The problem is wss if anyone using reverse proxy add this lines in location / in nginx and problem will be fixed.
`
location / {
        proxy_pass http://x.x.x.x:3170/;
        include proxy_params;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

`

**Comment by Systemko** [comment]
I can confirm that this is a configuration issue. If you are running your hoppscotch instance under https, you have to use secure web socket connection in VITE_BACKEND_WS_URL(**wss** not ws). But there is still an issue that we've stumbled upon. You really need to delete cookies from your browser because hoppscotch graphql backend path is cached.
P.S. To delete cookies in google chrome you need to proceed to this [link](chrome://settings/content/all), find your hoppscotch site address and click the bin icon.

**Comment by am071092** [comment]
Hi, I am facing the same issue as above, even after using secure web connection via wss. Is there a fix for this?

**Comment by Systemko** [comment]
> Hi, I am facing the same issue as above, even after using secure web connection via wss. Is there a fix for this?

Did you clear hoppscotch cache in your browser as I had mentioned above?

**Comment by QuentinDEME97** [comment]
Using Traefik, the only thing I changed is:

```
urls:
      base: "https://app.hoppscotch"
      shortcode: "https://app.hoppscotch."
      admin: "https://admin.hoppscotch"
      backend:
        gql: "https://backend.hoppscotch/graphql"
        ws: "wss://backend.hoppscotch/graphql" <-- THIS from ws: to wss:
        api: "https://backend.hoppscotch./v1"
      redirect: "https://app.hoppscotch."
      whitelistedOrigins: "https://backend.hoppscotch.,https://app.hoppscotch.,https://admin.hoppscotch."
```
