### ISSUE TITLE
[feature]: Add translations for admin section

### ISSUE THREAD

**Issue by giosueDelgado** [hoppscotch/hoppscotch#3343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Using the self hosted installation I see that there is not sections translated in the admin panel.

### Why should this be worked on?

I think at least the english translation is useful to add to make more easy to understand.

**Comment by liyasthomas** [comment]
Normally this shouldn't happen. All strings in the admin dashboard should have English translations. @JoelJacobStephen can you take a look at this?

**Comment by JoelJacobStephen** [comment]
@giosueDelgado I am unable to reproduce this issue on my end. Can you elaborate the steps you have taken so as to reproduce this issue?

**Comment by giosueDelgado** [comment]
Sure for this I created this configuration on docker-compose:

```yml
api-gui:

    image: hoppscotch/hoppscotch:2023.8.0
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"
    environment:
      - DATABASE_URL=postgresql://...
      - JWT_SECRET=
      - TOKEN_SALT_COMPLEXITY=10
      - MAGIC_LINK_TOKEN_VALIDITY=3
      - REFRESH_TOKEN_VALIDITY=604800000
      - ACCESS_TOKEN_VALIDITY=86400000
      - SESSION_SECRET=
      - REDIRECT_URL=https://
      - WHITELISTED_ORIGINS=https://
      - VITE_ALLOWED_AUTH_PROVIDERS=EMAIL
      - MAILER_SMTP_URL=smtps://...
      - MAILER_ADDRESS_FROM='"API Gui"... '
      - RATE_LIMIT_TTL=60
      - RATE_LIMIT_MAX=100
      - VITE_BASE_URL=https://...
      - VITE_SHORTCODE_BASE_URL=https://...
      - VITE_ADMIN_URL=https://...
      - VITE_BACKEND_GQL_URL=https://...
      - VITE_BACKEND_WS_URL=wss://...
      - VITE_BACKEND_API_URL=https://...
      #- VITE_APP_TOS_LINK=https://docs.hoppscotch.io/terms
      #- VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/privacy
    depends_on:
      - postgres
```

And If you go on localhost:3100 you will not see translation but something like this:
![image](https://github.com/hoppscotch/hoppscotch/assets/11545723/5d1ccb6f-9e31-4004-80d6-f872ce30f86b)

As you can see differents label are not translated and my browser is in English

Thanks
