### ISSUE TITLE
[bug]: Can not start docker Install and build

### ISSUE THREAD

**Issue by MinhFrostNhat** [hoppscotch/hoppscotch#3414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have new docker image and I try to run following the document and I found this ` Backend Server | 
Backend Server | PrismaClientInitializationError: Can't reach database server at `hoppscotch-db`:`5432`
Backend Server | 
Backend Server | Please make sure your database server is running at `hoppscotch-db`:`5432`.
` `
https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build  the default Postgres still use in new docker image? Please help me thank you! 

### Steps to reproduce

https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build  
https://hub.docker.com/r/hoppscotch/hoppscotch

### Environment

Deploy preview

### Version

Self-hosted

**Comment by annleefores** [comment]
If you are running the containers on their own, without docker compose, you will need to have an external postgres db as described [here](https://docs.hoppscotch.io/documentation/self-host/community-edition/prerequisites#postgres-database)

I believe this line in the documentation is intended for docker compose rather than docker container.
>  you can also use our default database shipped within the docker container postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch

**Comment by juanitolaguna** [comment]
@annleefores But what are the correct db credentials for the AIO version then?

**Comment by annleefores** [comment]
@juanitolaguna as far as I know, you need to set up your own PostgreSQL database and use its credentials. There might be some confusion regarding this in the documentation. I have raised an issue to get a clear idea https://github.com/hoppscotch/docs/issues/149#issue-1941481535

**Comment by juanitolaguna** [comment]
@annleefores Yes I thought the db is within the container. Then I realised that i have to add the db container.

So this approach has worked for me.

```yml
hoppscotch:
    image: hoppscotch/hoppscotch 
    env_file:
      - .env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"

  hoppscotch-db:
    image: postgres:15
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
```
