### ISSUE TITLE
[bug]: Self-Hosted AIO - POST http://localhost:3170/graphql net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by owlpro** [hoppscotch/hoppscotch#3435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

hi, after setup AIO with docker from hoppscotch/hoppscotch:2023.8.1
(https://hub.docker.com/layers/hoppscotch/hoppscotch/2023.8.1/images/sha256-8c4ea4157035f6ae5ac58d36d82e423287ec815f54c1350d00dde7f03236a112?context=explore)

i got this error
![Screenshot from 2023-10-08 14-49-52](https://github.com/hoppscotch/hoppscotch/assets/44808170/3ebc8275-477d-4e0a-9fb0-67672ba61f3b)

when i refresh from cache (Ctrl + Shift + R) there is no problem
but when i simple refresh (Ctrl + R) get this error

Cache Refresh `import_meta_env` variable values:
![1111](https://github.com/hoppscotch/hoppscotch/assets/44808170/478a615d-6564-4c57-874b-0270db85fb08)

Simple Refresh `import_meta_env` variable values:
![Screenshot from 2023-10-08 14-54-43](https://github.com/hoppscotch/hoppscotch/assets/44808170/a7b8ab65-01a1-42b0-aeac-ef555bd7fa03)

### Steps to reproduce

**reproduce with docker:**

```version: '1.0'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: psg_user
      POSTGRES_PASSWORD: psg_pass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hoppscotch-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - hoppscotch-network

  hoppscotch:
    image: hoppscotch/hoppscotch
    restart: always
    env_file: ./.env
    ports:
      - 3099:3000
      - 3100:3100
      - 3170:3170
    networks:
      - hoppscotch-network

volumes:
  pgdata:
    driver: local

networks:
  hoppscotch-network:
    driver: bridge```

### Environment

Production

### Version

Self-hosted

**Comment by owlpro** [comment]
Is there a quick fix?
For example, a change in Docker or whatever

**Comment by icsy7867** [comment]
I am getting this as well.  When I click the magic link, the console is showing attempts made to localhost:3170, instead of my set domain-name.com:3170

However the main site loads just fine.

**Comment by icsy7867** [comment]
I went ahead and converted to the three separate containers:
hoppscotch-frontend
hoppscotch-backend
hoppscotch-admin

And I am getting the same errors.  After successfully receiving the magic links and clicking them the console is showing all "localhost" URLS, instead of the URLS I have set in the .env file.

A hard cache reload fixes this, until I try to log in again, and then those variables are saved in my session.

**Comment by owlpro** [comment]
> I am using the AIO container of Hoppscotch and getting the same error while hosting on a domain.
> 
> ![Screenshot at Jan 03 17-40-28](https://private-user-images.githubusercontent.com/143718087/293909527-18252bed-121a-42fc-8859-06c3add9f46c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYyMDMsIm5iZiI6MTcwNDM2NTkwMywicGF0aCI6Ii8xNDM3MTgwODcvMjkzOTA5NTI3LTE4MjUyYmVkLTEyMWEtNDJmYy04ODU5LTA2YzNhZGQ5ZjQ2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMDU4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjU3M2RmMTI3NWEzYzY5YWY3ZGUxZjA3ZDk4MDY5NTA3YzllNGU3ZGRlMzdlMGJkOGIxZDQ0MTY0ZmQwYTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._YqlZagW050iH9GRdd2ElQH5qu0XgfvEFHSi8jtcvz8)
> 
> Replace all localhost URLs to domain URLs but didn't get success.
> 
> Can someone help me to fix this?

use this docker-compose.yml to fix:
```yml
version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hoppscotch-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - hoppscotch-network
  
  hoppscotch-backend:
    image: hoppscotch/hoppscotch-backend
    restart: always
    env_file: ./prod.env
    ports:
      - 3170:3170
    networks:
      - hoppscotch-network

  hoppscotch-frontend:
    image: hoppscotch/hoppscotch-frontend
    restart: always
    env_file: ./prod.env
    ports:
      - 3099:8080
    networks:
      - hoppscotch-network

 
  hoppscotch-admin:
    image: hoppscotch/hoppscotch-admin
    restart: always
    env_file: ./prod.env
    ports:
      - 3100:8080
    networks:
      - hoppscotch-network

volumes:
  pgdata:
    driver: local

networks:
  hoppscotch-network:
    driver: bridge

```
