### ISSUE TITLE
Magic Link Toen expired immediately with non-default timezone

### ISSUE THREAD

**Issue by WestFarmer** [hoppscotch/hoppscotch#3577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

login with email, the token is expired immediately. 

### Steps to reproduce

I am deploying with kubernetes and mounted a timezone file like this:
```
volumeMounts:     
- name: tz
  mountPath: /etc/localtime
volumes:
- name: tz
  hostPath:
  path: /usr/share/zoneinfo/Asia/Shanghai
```

I am doing this is because I am in UTC+8, to see correct time such as in logs.

but this will fail the email magic link login 

### Environment

Production

### Version

Self-hosted
