### ISSUE TITLE
[bug]: Login model not show email option, and toast `Unable to load auth providers`

### ISSUE THREAD

**Issue by aliuq** [hoppscotch/hoppscotch#3733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Login model not show email option, and toast `Unable to load auth providers`

I found `plantform` is undefined

![image](https://github.com/hoppscotch/hoppscotch/assets/11707934/86dcb1d1-6fd0-48bb-a276-9659e9812712)

### Steps to reproduce

Hoppscotch version is `2023.12.2`

`.env`

```env
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:xxxxx@hoppscotch-db:5432/hoppscotch

ENABLE_SUBPATH_BASED_ACCESS=true
PUID=1026
PGID=100
LANG=zh_CN.utf8

# # Auth Tokens Config
JWT_SECRET=xxxxxxxxxxxxxxxxxxx
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000
ACCESS_TOKEN_VALIDITY=86400000
SESSION_SECRET=xxxxxxxxxxxxxxxxxxxxxxxx

WHITELISTED_ORIGINS=/backend,/,/admin
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL

# # Mailer config ---- smtps://user@domain.com:pass@smtp.domain.com
MAILER_SMTP_URL="smtps://no-reply@xxxxxxx.com:xxxxxxxxxxxxxxx@smtp.xxxxxxx.com"
# MAILER_ADDRESS_FROM=no-reply@xxxxxxx.com
MAILER_ADDRESS_FROM='"From xxxx Hoppscotch" <no-reply@xxxxxxx.com>'

# # Rate Limit Config
RATE_LIMIT_TTL=60
RATE_LIMIT_MAX=100

#-----------------------Frontend Config------------------------------#

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy
```

`docker-compose.yaml`

```yaml
version: "3.7"
services:
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - 3000:80
  hoppscotch-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxxxxx
      POSTGRES_DB: hoppscotch
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10
```

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@aliuq Can you check the logs in the container for any error messages being thrown and share them here.

**Comment by aliuq** [comment]
@balub I didn’t see any error type information from the logs.

**Comment by aliuq** [comment]
Error is always exist. I guessed is wrong configuration

my `docker-compose.yaml` file

```yaml
version: "3.7"
services:
  hoppscotch:
    image: hoppscotch/hoppscotch:2023.12.2
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - 3000:80
  hoppscotch-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxxxxxxx
      POSTGRES_DB: hoppscotch
      PGDATA: /pg-data
    volumes:
      - ./pgdata:/pg-data
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 5s
      retries: 10
```

my `.env` file, e.g. origin is `https://hoppscotch.xxx.xxx.xx`

```env
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:xxxx@hoppscotch-db:5432/hoppscotch

ENABLE_SUBPATH_BASED_ACCESS=true
PUID=1026
PGID=100
LANG=zh_CN.utf8

# # Auth Tokens Config
JWT_SECRET=xxxxxxxxxxxxxxxxxx
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY="604800000"
ACCESS_TOKEN_VALIDITY="86400000"
SESSION_SECRET=xxxxxxxxxxxxxxxxxxxxx

# Hoppscotch App Domain Config
REDIRECT_URL="http://localhost:3000"
WHITELISTED_ORIGINS="https://hoppscotch.xxx.xxx.xx/backend,https://hoppscotch.xxx.xxx.xx,https://hoppscotch.xxx.xxx.xx/admin"
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL

# Google Auth Config
# GOOGLE_CLIENT_ID="*****"
# GOOGLE_CLIENT_SECRET="*****"
# GOOGLE_CALLBACK_URL=/backend/v1/auth/google/callback
# # GOOGLE_CALLBACK_URL=${BASE_URL}/backend/v1/auth/google/callback
# GOOGLE_SCOPE=email,profile

# Github Auth Config
# GITHUB_CLIENT_ID=*****
# GITHUB_CLIENT_SECRET=****
# GITHUB_CALLBACK_URL=${BASE_URL}/backend/v1/auth/github/callback
# GITHUB_SCOPE=user:email

# Microsoft Auth Config
# MICROSOFT_CLIENT_ID=*****
# MICROSOFT_CLIENT_SECRET=*****
# MICROSOFT_CALLBACK_URL=${BASE_URL}/backend/v1/auth/microsoft/callback
# MICROSOFT_SCOPE=user.read
# MICROSOFT_TENANT=common

# # Mailer config ---- smtps://user@domain.com:pass@smtp.domain.com
MAILER_SMTP_URL="smtps://no-reply@xxxxxxx.com:xxxxxxxxxxxxxx@smtp.xxxxx.xxxx.com"
MAILER_ADDRESS_FROM='"From xxxxxxxx Hoppscotch" <no-reply@xxxxxxx.com>'

# # Rate Limit Config
RATE_LIMIT_TTL=60
RATE_LIMIT_MAX=100


#-----------------------Frontend Config------------------------------#

# # Base URLs
# VITE_BASE_URL=http://192.168.2.10:3000
VITE_BASE_URL=https://hoppscotch.xxx.xxx.xx
VITE_SHORTCODE_BASE_URL=https://hoppscotch.xxx.xxx.xx
VITE_ADMIN_URL=https://hoppscotch.xxx.xxx.xx/admin

# # # Backend URLs
VITE_BACKEND_GQL_URL=https://hoppscotch.xxx.xxx.xx/backend/graphql
VITE_BACKEND_WS_URL=wss://hoppscotch.xxx.xxx.xx/backend/graphql
VITE_BACKEND_API_URL=https://hoppscotch.xxx.xxx.xx/backend/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

```

Logs here.

[logs.txt](https://github.com/hoppscotch/hoppscotch/files/13954086/logs.txt)
