### ISSUE TITLE
[bug]: Can't use GITHUB auth in k8s installation

### ISSUE THREAD

**Issue by Brainpitcher** [hoppscotch/hoppscotch#3813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello. I am experiencing difficulties with authorization through GITHUB. The problem is that after a correct request for authorization data I get a 404 page.   Nowhere in the logs of the ingress controller I don't see the 404 page and I don't understand who gives it. (logs attached). As you can see everywhere only codes 200 and 304 and everything looks just fine, but there is no authorization. Callback paths are identical, everything has been checked more than once. All handles give 200 code (logs attached)
I am using a valid ssl certificate from ltes encrypt in my cluster. 
I note that both admin panel and backend are accessible, authorization via magic link works correctly, which indicates that the backend is alive.
env:
`      - name: GITHUB_CALLBACK_URL
        value: "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback"`
curl of callback path:
`curl -i https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback
HTTP/2 200 
date: Thu, 08 Feb 2024 07:14:25 GMT
content-type: text/html; charset=utf-8
content-length: 5625
accept-ranges: bytes
etag: "s8hmjb4c9"
last-modified: Wed, 07 Feb 2024 13:23:35 GMT
strict-transport-security: max-age=15724800; includeSubDomains`

ingress controller's logs:
`10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6 HTTP/2.0" 200 5625 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 85 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 5625 0.001 200 b94b150e14f2613fc094c484b3756811
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-cyrillic-ext-wght-normal-1c3007b8.woff2 HTTP/2.0" 200 27284 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 195 0.003 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 27284 0.003 200 7b8dcf85bc5274798341a4019453e5e0
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-cyrillic-wght-normal-eba94878.woff2 HTTP/2.0" 200 17600 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 50 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 17600 0.002 200 b7e682c22b704e823219ee902596928a
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-greek-ext-wght-normal-81f77e51.woff2 HTTP/2.0" 200 12732 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 51 0.001 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 12732 0.001 200 1ad95e588917643cfa2094de0f966ad1
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-greek-wght-normal-d92c6cbc.woff2 HTTP/2.0" 200 22480 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 48 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 22480 0.002 200 a3142c326beb36c9285dae5401d39889
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-vietnamese-wght-normal-15df7612.woff2 HTTP/2.0" 200 10540 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 51 0.001 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 10540 0.002 200 1d1bd39a3937d8efae1e94c5fb8fa119
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-latin-ext-wght-normal-a2bfd9fe.woff2 HTTP/2.0" 200 79940 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 51 0.003 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 79940 0.003 200 561e67556741036722a95badb4a40a69
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/inter-latin-wght-normal-88df0b5a.woff2 HTTP/2.0" 499 0 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 48 0.000 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 0 0.001 - 16b5f7d55eb2bc1aadbdc77a27adede7
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/roboto-mono-cyrillic-ext-wght-normal-d694a640.woff2 HTTP/2.0" 200 35888 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 57 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 35888 0.002 200 01696b916a88bebc9daed9cde74c00ab
10.231.1.1 - - [08/Feb/2024:07:23:05 +0000] "GET /assets/roboto-mono-cyrillic-wght-normal-f5503b96.woff2 HTTP/2.0" 499 0 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 54 0.000 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 0 0.001 - 64f36a7bcf32c8e3477ec908476c0dc5
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "GET /sw.js HTTP/2.0" 200 6177 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 21 0.001 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 6177 0.001 200 da9d2c83c63a22ba7f4141c73419f3e2
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "POST /backend/graphql HTTP/2.0" 200 1563 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 187 0.072 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 1563 0.016 200 8b7c5086a83ff950e0ca73febed84234
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "POST /backend/graphql HTTP/2.0" 200 1588 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 372 0.013 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 1588 0.013 200 a227f2dd2defd6a555dc842fd7a7a342
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "POST /backend/graphql HTTP/2.0" 200 1563 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 184 0.016 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 1563 0.016 200 a2dae68c3fe7606ef345954f3f44aba0
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "POST /backend/graphql HTTP/2.0" 200 1563 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 419 0.021 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 1563 0.021 200 1d876aa9de3c309b99bfff22e6f1c6eb
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "POST /backend/graphql HTTP/2.0" 200 1588 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 371 0.024 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 1588 0.023 200 2bdc9ce77b8ca7af7f2d5daa8f095d31
10.231.1.1 - - [08/Feb/2024:07:23:06 +0000] "GET /images/states/dark/youre_lost.svg HTTP/2.0" 200 35496 "https://hoppscotch.local.adc-tech.ru/v1/auth/github/callback?code=0e6cc5bfec24482595f5&state=pjTMik09wHxSzn6WSxkvMVy6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 65 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.152:80 35496 0.002 200 23a1310b7e1c520820f7d37c52832e9f
10.231.1.1 - - [08/Feb/2024:07:23:07 +0000] "GET /sw.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0" 133 0.002 [hoppscotch-hoppscotch-80] [] 10.231.2.153:80 0 0.001 304 a45d1d68df9a40c16f7bc2f88b7777c6`

helm template render of ingress and service:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch.local.adc-tech.ru
  namespace: "hoppscotch"
  labels:
    app.kubernetes.io/name: hoppscotch
    app.kubernetes.io/instance: hoppscotch
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-adc
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: hoppscotch.local.adc-tech.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hoppscotch
            port:
              number: 80
  tls:
  - hosts:
    - hoppscotch.local.adc-tech.ru
    secretName: hoppscotch-local-tls

kind: Service
apiVersion: v1
metadata:
  name: hoppscotch
  namespace: "hoppscotch"
  labels:
    app.kubernetes.io/name: hoppscotch
    app.kubernetes.io/instance: hoppscotch
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
  selector:
    app.kubernetes.io/name: hoppscotch
    app.kubernetes.io/instance: hoppscotch
```

### Steps to reproduce

1. just represent it

### Environment

Production

### Version

Self-hosted
