### ISSUE TITLE
[bug]: not able to run hoppscotch-backend latest in docker compose

### ISSUE THREAD

**Issue by mtariqsajid** [hoppscotch/hoppscotch#3994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

whenever run hoppscotch-backend it always show the error in docker

*error logs*
```
hoppscotch-backend-1   | Progress: resolved 3, reused 0, downloaded 2, added 0
hoppscotch-backend-1   | Progress: resolved 3, reused 0, downloaded 3, added 0
hoppscotch-backend-1   | Progress: resolved 4, reused 0, downloaded 3, added 0
hoppscotch-backend-1   | Progress: resolved 5, reused 0, downloaded 4, added 0
hoppscotch-backend-1   | Progress: resolved 5, reused 0, downloaded 5, added 0
hoppscotch-backend-1   | Progress: resolved 6, reused 0, downloaded 5, added 0
hoppscotch-backend-1   | Packages: +6
hoppscotch-backend-1   | ++++++
hoppscotch-backend-1   | Progress: resolved 6, reused 0, downloaded 6, added 6, done
hoppscotch-backend-1   | .../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
hoppscotch-backend-1   | .../node_modules/@prisma/engines postinstall: Done
hoppscotch-backend-1   | .../prisma@5.12.1/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
hoppscotch-backend-1   | .../prisma@5.12.1/node_modules/prisma preinstall: Done
hoppscotch-backend-1   | Prisma schema loaded from prisma/schema.prisma
hoppscotch-backend-1   | Datasource "db": PostgreSQL database "postman", schema "public" at "postgres:5432"
postgres-1             | 2024-04-21 20:41:36.072 UTC [69] LOG:  could not receive data from client: Connection reset by peer
hoppscotch-backend-1   | 
hoppscotch-backend-1   | 5 migrations found in prisma/migrations
hoppscotch-backend-1   | 
hoppscotch-backend-1   | Applying migration `20230406064219_init`
hoppscotch-backend-1   | Applying migration `20231106120154_embeds_addition`
hoppscotch-backend-1   | Applying migration `20231124104640_infra_config`
hoppscotch-backend-1   | Applying migration `20231130082054_collection_headers`
hoppscotch-backend-1   | Applying migration `20240226053141_full_text_search_additions`
hoppscotch-backend-1   | 
hoppscotch-backend-1   | The following migration(s) have been applied:
hoppscotch-backend-1   | 
hoppscotch-backend-1   | migrations/
hoppscotch-backend-1   |   └─ 20230406064219_init/
hoppscotch-backend-1   |     └─ migration.sql
hoppscotch-backend-1   |   └─ 20231106120154_embeds_addition/
hoppscotch-backend-1   |     └─ migration.sql
hoppscotch-backend-1   |   └─ 20231124104640_infra_config/
hoppscotch-backend-1   |     └─ migration.sql
hoppscotch-backend-1   |   └─ 20231130082054_collection_headers/
hoppscotch-backend-1   |     └─ migration.sql
hoppscotch-backend-1   |   └─ 20240226053141_full_text_search_additions/
hoppscotch-backend-1   |     └─ migration.sql
hoppscotch-backend-1   |       
hoppscotch-backend-1   | All migrations have been successfully applied.
hoppscotch-backend-1 exited with code 0

```

### Steps to reproduce

exact docker images version:
- hoppscotch-admin: hoppscotch/hoppscotch-admin:2024.3.0
- hoppscotch-frontend: hoppscotch/hoppscotch-frontend:2024.3.0
- hoppscotch-backend: hoppscotch/hoppscotch-backend:2024.3.0

this is the docker compose file that i am running in 
docker version: 
docker compose version:

docker-compose.yml

```yml
services:
 postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postman
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  hoppscotch-frontend:
    image: hoppscotch/hoppscotch-frontend
    ports:
      - "3000:3000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

  hoppscotch-backend:
    image: hoppscotch/hoppscotch-backend
    ports:
      - "3170:3170"
    env_file: .env
    command: pnpx prisma migrate deploy
    depends_on:
      - postgres

  hoppscotch-admin:
    image: hoppscotch/hoppscotch-admin
    ports:
      - "3100:3100"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres

```

the env

```env
# -----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL="postgresql://root:root@postgres:5432/postman"# or replace with your database URL"

# Auth Tokens Config
JWT_SECRET=secretcode123
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000
ACCESS_TOKEN_VALIDITY=86400000
SESSION_SECRET=anothersecretcode123

# Hoppscotch App Domain Config
REDIRECT_URL=http://localhost:3000
WHITELISTED_ORIGINS=http://localhost:3170,http://localhost:3000,http://localhost:3100
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL

# Mailer config
MAILER_SMTP_URL="smtps://377bd90ss7c20b74@mailtrap.io:8c6bdddd01f7ad6347@sandbox.smtp.mailtrap.io"
MAILER_ADDRESS_FROM=from@example.com

# Rate Limit Config
RATE_LIMIT_TTL=60
RATE_LIMIT_MAX=100

# -----------------------Frontend Config------------------------------#

# Base URLs
VITE_BASE_URL=http://localhost:3000
VITE_SHORTCODE_BASE_URL=http://localhost:3000
VITE_ADMIN_URL=http://localhost:3100

# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3170/graphql
VITE_BACKEND_WS_URL=wss://localhost:3170/graphql
VITE_BACKEND_API_URL=http://localhost:3170/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

ENABLE_SUBPATH_BASED_ACCESS=false

```

### Environment

Production

### Version

Self-hosted
