### ISSUE TITLE
[bug]: Do not have Email / SSO Sign in

### ISSUE THREAD

**Issue by seniyakk** [hoppscotch/hoppscotch#4185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello. 
When I try to log in to Hoppscotch I have 3 options:
- Github
- Google
- Microsoft
<img width="650" alt="Screenshot 2024-07-13 at 10 17 19" src="https://github.com/user-attachments/assets/5ba254c1-34fe-449f-80b8-fb5ac557149f">
<img width="578" alt="Screenshot 2024-07-13 at 10 24 20" src="https://github.com/user-attachments/assets/d754a6b1-7eba-4672-9a7c-e9468a60aeb8">

The instructions write that I can log in via email or SSO.

**How to log in via email or SSO?**

My docker-compose.yml

```
services:
  hoppscotch:
    container_name: hoppscotch
    restart: unless-stopped
    image: hoppscotch/hoppscotch
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    command: pnpx prisma migrate deploy
    labels:
      traefik.enable: true

      traefik.http.routers.hoppscotch-http.rule: Host(`hoppscotch.yourserver`)
      traefik.http.routers.hoppscotch-http.entrypoints: web
      traefik.http.routers.hoppscotch-http.middlewares: https-redirect

      traefik.http.routers.hoppscotch-https.rule: Host(`hoppscotch..yourserver`)
      traefik.http.routers.hoppscotch-https.entrypoints: websecure
      traefik.http.routers.hoppscotch-https.tls: true
      traefik.http.routers.hoppscotch-https.tls.certresolver: prod

    environment:
      #-----------------------Backend Config------------------------------#
      DATABASE_URL: postgresql://hoppscotch:xB9pNCiBYTixLNQBrwmyGHMnQ7N6aWAXUCp5QEhi@hoppscotch-db:5432/hoppscotch # or replace with your database URL

      # Auth Tokens Config
      JWT_SECRET: secret
      TOKEN_SALT_COMPLEXITY: 10
      MAGIC_LINK_TOKEN_VALIDITY: 3
      REFRESH_TOKEN_VALIDITY: 604800000
      ACCESS_TOKEN_VALIDITY: 86400000
      SESSION_SECRET: anothersecret

      # Hoppscotch App Domain Config
      REDIRECT_URL: http://localhost:3000
      WHITELISTED_ORIGINS: http://localhost:3170,http://localhost:3000,http://localhost:3100
      VITE_ALLOWED_AUTH_PROVIDERS: EMAIL

      # Github Auth Config
      GITHUB_CLIENT_ID: text
      GITHUB_CLIENT_SECRET: text
      GITHUB_CALLBACK_URL: http://localhost:3170/v1/auth/github/callback
      GITHUB_SCOPE: user:email

      # Microsoft Auth Config
      MICROSOFT_CLIENT_ID: text
      MICROSOFT_CLIENT_SECRET: text
      MICROSOFT_CALLBACK_URL: http://localhost:3170/v1/auth/microsoft/callback
      MICROSOFT_SCOPE: user.read
      MICROSOFT_TENANT: common

      # # Mailer config
      MAILER_SMTP_URL: smtps://user@domain.com:pass@smtp.domain.com
      MAILER_ADDRESS_FROM: from@example.com

      # Rate Limit Config
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_MAX: 100

      #-----------------------Frontend Config------------------------------#

      # Base URLs
      VITE_BASE_URL: http://localhost:3000
      VITE_SHORTCODE_BASE_URL: http://localhost:3000
      VITE_ADMIN_URL: http://localhost:3100

      # Backend URLs
      VITE_BACKEND_GQL_URL: http://localhost:3170/graphql
      VITE_BACKEND_WS_URL: wss://localhost:3170/graphql
      VITE_BACKEND_API_URL: http://localhost:3170/v1

      # Terms Of Service And Privacy Policy Links (Optional)
      VITE_APP_TOS_LINK: https://docs.hoppscotch.io/support/terms
      VITE_APP_PRIVACY_POLICY_LINK: https://docs.hoppscotch.io/support/privacy

      ENABLE_SUBPATH_BASED_ACCESS: false    
    networks:
        - traefik
        - hoppscotch
    ports:
        - 3000:3000
        - 3100:3100
        - 3170:3170
        - 3080:80

  hoppscotch-db:
    container_name: hoppscotch-db
    image: postgres:15
    ports:
      - 5432:5432
    user: postgres
    environment:
      POSTGRES_USER: hoppscotch
      POSTGRES_PASSWORD: xB9pNCiBYTixLNQBrwmyGHMnQ7N6aWAXUCp5QEhi
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hoppscotch

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $VOLUMES_PATH_PREFIX/hoppscotch/volumes/db

networks:
  traefik:
    external: true
  hoppscotch:
    name: hoppscotch
```

### Steps to reproduce

1. Compose up docker-compose.yml
2. Try to login

### Environment

Production

### Version

Self-hosted
