### ISSUE TITLE
[bug]: 2024.7.1 backend docker image start failed with error "listen tcp :80: bind: permission denied"

### ISSUE THREAD

**Issue by StoneMoe** [hoppscotch/hoppscotch#4264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I followed the documetation to run self-host hoppscotch with AIO container option, the container log says:
```
App/Admin Dashboard Caddy | Error: loading initial config: loading new config: http app module: start: listening on :80: listen tcp :80: bind: permission denied
```
seems like Caddy somehow decided to bind to port 80 and failed due to permission issue.

then I also tried to run it with the separated service containers, and turns out `admin` and `frontend` container started successfully, but the `backend` container reported the exact same error log.

### Steps to reproduce

1. fresh environment
2. run with AIO container image, with the compose and env file below
3. see logs report port binding error

compose.yml:
```
version: '3.8'

services:
  frontend:
    image: hoppscotch/hoppscotch-frontend:2024.7.1
    ports:
      - "3000:3000"
    env_file:
      - stack.env
    restart: unless-stopped

  backend:
    image: hoppscotch/hoppscotch-backend:2024.7.1
    ports:
      - "3170:3170"
    env_file:
      - stack.env
    restart: unless-stopped

  admin:
    image: hoppscotch/hoppscotch-admin:2024.7.1
    ports:
      - "3100:3100"
    env_file:
      - stack.env
    restart: unless-stopped
  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: hoppscotch
      POSTGRES_USER: hoppscotch

```

stack.env:
```
DATABASE_URL=postgresql://hoppscotch:hoppscotch@db:5432/hoppscotch # or replace with your database URL
JWT_SECRET=abcdefg0000000
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000 # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY=86400000 # Default validity is 1 day (86400000 ms) in ms
SESSION_SECRET=hijklmn1111111
ALLOW_SECURE_COOKIES=false
REDIRECT_URL=http://hop.home.lan:3000
WHITELISTED_ORIGINS=http://hop.home.lan:3170,http://hop.home.lan:3000,http://hop.home.lan:3100
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL
MAILER_SMTP_ENABLE=true
MAILER_USE_CUSTOM_CONFIGS=false
MAILER_ADDRESS_FROM=<hoppscotch@home.lan>
MAILER_SMTP_URL=
RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP
VITE_BASE_URL=http://hop.home.lan:3000
VITE_SHORTCODE_BASE_URL=http://hop.home.lan:3000
VITE_ADMIN_URL=http://hop.home.lan:3100
VITE_BACKEND_GQL_URL=http://hop.home.lan:3170/graphql
VITE_BACKEND_WS_URL=wss://hop.home.lan:3170/graphql
VITE_BACKEND_API_URL=http://hop.home.lan:3170/v1
VITE_APP_TOS_LINK=http://example.com
VITE_APP_PRIVACY_POLICY_LINK=http://example.com
ENABLE_SUBPATH_BASED_ACCESS=false
```

### Environment

Production

### Version

Self-hosted
