### ISSUE TITLE
[bug]:  Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by celevra** [hoppscotch/hoppscotch#4347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

after Upgrade to the newest version and a migrate deploy i recive following error:

```
hoppscotch-aio              | Backend Server | [Nest] 37  - 09/13/2024, 7:01:55 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'split')
hoppscotch-aio              | Backend Server | TypeError: Cannot read properties of undefined (reading 'split')
hoppscotch-aio              | Backend Server |     at InfraConfigService.getAllowedAuthProviders (/dist/backend/dist/infra-config/infra-config.service.js:266:13)
hoppscotch-aio              | Backend Server |     at AuthService.getAuthProviders (/dist/backend/dist/auth/auth.service.js:248:40)
hoppscotch-aio              | Backend Server |     at AuthController.getAuthProviders (/dist/backend/dist/auth/auth.controller.js:41:50)
hoppscotch-aio              | Backend Server |     at /dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/router/router-execution-context.js:38:29
hoppscotch-aio              | Backend Server |     at InterceptorsConsumer.transformDeferred (/dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)
hoppscotch-aio              | Backend Server |     at /dist/backend/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_class-transformer@0.5.1_class-validator@0.14.1_refl_i5vxtddbnp5qhu6jmywguprp3e/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:18:86
hoppscotch-aio              | Backend Server |     at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
hoppscotch-aio              | Backend Server |     at bound (node:async_hooks:238:16)
hoppscotch-aio              | Backend Server |     at Observable._subscribe (/dist/backend/node_modules/.pnpm/rxjs@7.6.0/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
hoppscotch-aio              | Backend Server |     at Observable._trySubscribe (/dist/backend/node_modules/.pnpm/rxjs@7.6.0/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
```

this is the entry in the env:

```
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL
```

### Steps to reproduce

i have no idea

### Environment

Production

### Version

Self-hosted

**Comment by dani** [comment]
For what it worth, I add this very same issue, because I started hoppscotch with a wrong DATA_ENCRYPTION_KEY (started a new instance with a newly generated DATA_ENCRYPTION_KEY, but restoring a postgres dump from another instance, which used a different DATA_ENCRYPTION_KEY). Once I've put back the correct DATA_ENCRYPTION_KEY everything is working

**Comment by kimcuong2407** [comment]
how can fix this. I have the same problem.

**Comment by mirarifhasan** [comment]
Thank you for bringing this to our attention! We're actively working on this type of issue and trying to reproduce it on our end.

If you're still experiencing the problem, could you share a snapshot of the InfraConfig table from your database? Feel free to mask or edit any sensitive data in the snapshot to ensure your information remains secure.

**Comment by kimcuong2407** [comment]
this is my table InfraConfig.
please check for me again.
thanks

Vào Th 4, 20 thg 11, 2024 vào lúc 13:08 Mir Arif Hasan <
***@***.***> đã viết:

**Comment by mschori** [comment]
Hey everyone
Today i experienced the same error. I think the problem comes from the file infra-config.service.ts at line 420. It looks to me, like the variable is not present and to call .split(',') on undefined is crashing the backend. 

![image](https://github.com/user-attachments/assets/3aafc685-e419-4032-9e5f-9b71d5182309)

This is a cropped screenshot of the database-table called InfraConfig. 

The variable is also set in the .env file.

Any suggestions for a fix?

**Comment by mschori** [comment]
> For what it worth, I add this very same issue, because I started hoppscotch with a wrong DATA_ENCRYPTION_KEY (started a new instance with a newly generated DATA_ENCRYPTION_KEY, but restoring a postgres dump from another instance, which used a different DATA_ENCRYPTION_KEY). Once I've put back the correct DATA_ENCRYPTION_KEY everything is working

Can you provide an example of a correct DATA_ENCRYPTION_KEY ?

**Comment by mschori** [comment]
That was the fix. Thank you. The first start of the aio container was executed with a different DATA_ENCRYPTION_KEY. Now it is working. The given error from the backend is completly missleading.

**Comment by kimcuong2407** [comment]
how to generate  DATA_ENCRYPTION_KEY valid
pls help me

Vào Th 6, 22 thg 11, 2024 vào lúc 20:57 Michael Schori <
***@***.***> đã viết:

**Comment by mirarifhasan** [comment]
@kimcuong2407 
You can use any string for DATA_ENCRYPTION_KEY. Just make sure, the string should be exactly 32 characters long.

**Comment by Breee** [comment]
No, it's still broken

**Comment by mirarifhasan** [comment]
Hi @Breee, could you please share the screenshot of the `InfraConfig` table from DB and the error log? It would really help us in investigating the issue better. Thanks!

**Comment by zenkraker** [comment]
@mirarifhasan Personally I am just trying to run hoppscotch for an internal test and I am facing this issue.

You can reproduce it by:

1. docker compose run --entrypoint sh hoppscotch-backend (suggested in the docs)
2. Shell opens up for hoppscotch-backend
3. Run command `pnpx prisma migrate deploy`
4. Exit shell
5.  hoppscotch-backend is now stopped and  hoppscotch-db is running6. 
7. Run the compose underneath with docker compose up

You will discover that:
hoppscotch-backend crashes and if you look inside its logs you will find --> Cannot read properties of undefined (reading 'split')

Env variable used:
DATA_ENCRYPTION_KEY="data encryption key with 32 char"

```
services:
  hoppscotch-frontend:
    container_name: hoppscotch-frontend
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: unless-stopped
    image: hoppscotch/hoppscotch-frontend

  # First run docker compose run --entrypoint sh containerNameOfBackend
  # pnpx prisma migrate deploy
  hoppscotch-backend:
    image: hoppscotch/hoppscotch-backend
    container_name: hoppscotch-backend
    ports:
      - 3170:3170      
      - 3180:80
    env_file:
      - .env
    # restart: unless-stopped
    volumes:
      # Uncomment the line below when modifying code. Only applicable when using the "dev" target.
      # - ./packages/hoppscotch-backend/:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - hoppscotch-db
    
  hoppscotch-admin:
    container_name: hoppscotch-admin
    ports:
      - 3100:3100
    env_file:
      - .env
    restart: unless-stopped
    image: hoppscotch/hoppscotch-admin
  hoppscotch-db:
    image: postgres:16-alpine
    container_name: hoppscotch-db
    ports:
      - 5432:5432
    volumes:
      - /apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=hoppscotch_user
      - POSTGRES_DB=hoppscotch_db

```
