### ISSUE TITLE
[bug]: When using AIO container startup, backend startup error occurs, http://localhost:3170/graphql Request error

### ISSUE THREAD

**Issue by hanchenxu** [hoppscotch/hoppscotch#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

docker-compost.yml content：
```
services:
  hoppscotch-aio:
    container_name: hoppscotch-aio
    image: hoppscotch/hoppscotch
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"
      - "3080:80"

  hoppscotch-db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
```
.env content：
```
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:password@127.0.0.1:5432/hoppscotch

# (Optional) By default, the AIO container (when in subpath access mode) exposes the endpoint on port 80. Use this setting to specify a different port if needed.
HOPP_AIO_ALTERNATE_PORT=80

# Auth Tokens Config
JWT_SECRET=*****
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000 # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY=86400000 # Default validity is 1 day (86400000 ms) in ms
SESSION_SECRET=*****

# Recommended to be true. Set to false if you are using http.
# Note: Some auth providers may not support http requests and may stop working when set to false.
ALLOW_SECURE_COOKIES=true

# Sensitive Data Encryption Key while storing in Database (32 character)
DATA_ENCRYPTION_KEY=*****

# Hoppscotch App Domain Config
REDIRECT_URL=http://localhost:3000
WHITELISTED_ORIGINS=http://localhost:3170,http://localhost:3000,http://localhost:3100
VITE_ALLOWED_AUTH_PROVIDERS=EMAIL

# Google Auth Config
GOOGLE_CLIENT_ID=*****
GOOGLE_CLIENT_SECRET=*****
GOOGLE_CALLBACK_URL=http://localhost:3170/v1/auth/google/callback
GOOGLE_SCOPE=email,profile

# Github Auth Config
GITHUB_CLIENT_ID=*****
GITHUB_CLIENT_SECRET=****
GITHUB_CALLBACK_URL=http://localhost:3170/v1/auth/github/callback
GITHUB_SCOPE=user:email

# Microsoft Auth Config
MICROSOFT_CLIENT_ID=*****
MICROSOFT_CLIENT_SECRET=*****
MICROSOFT_CALLBACK_URL=http://localhost:3170/v1/auth/microsoft/callback
MICROSOFT_SCOPE=user.read
MICROSOFT_TENANT=common

# Mailer config
MAILER_SMTP_ENABLE=true
MAILER_USE_CUSTOM_CONFIGS=true
MAILER_ADDRESS_FROM=<from@example.com>
MAILER_SMTP_URL=smtps://user@domain.com:pass@smtp.domain.com # used if custom mailer configs is false
# The following are used if custom mailer configs is true
MAILER_SMTP_HOST=*****
MAILER_SMTP_PORT=25
MAILER_SMTP_SECURE=true
MAILER_SMTP_USER=*****
MAILER_SMTP_PASSWORD=*****
MAILER_TLS_REJECT_UNAUTHORIZED=true

# Rate Limit Config
RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP

#-----------------------Frontend Config------------------------------#

# Base URLs
VITE_BASE_URL=http://localhost:3000
VITE_SHORTCODE_BASE_URL=http://localhost:3000
VITE_ADMIN_URL=http://localhost:3100

# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3170/graphql
VITE_BACKEND_WS_URL=wss://localhost:3170/graphql
VITE_BACKEND_API_URL=http://localhost:3170/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

# Set to `true` for subpath based access
ENABLE_SUBPATH_BASED_ACCESS=false
```

### Steps to reproduce

1.start server : docker-compose up -d
2.docker logs ******：
```
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7249537,"msg":"using provided configuration","config_file":"/etc/caddy/aio-multiport-setup.Caddyfile","config_adapter":"caddyfile"}
App/Admin Dashboard Caddy | {"level":"warn","ts":1730770807.7272987,"logger":"admin","msg":"admin endpoint disabled"}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7282968,"logger":"http.log","msg":"server running","name":"srv2","protocols":["h1","h2","h3"]}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7283773,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7284281,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7284741,"msg":"serving initial configuration"}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.728994,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000349d80"}
App/Admin Dashboard Caddy | {"level":"warn","ts":1730770807.7504556,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/root/.local/share/caddy","instance":"61e8f835-542d-4971-9734-12540bf13aaa","try_again":1730857207.750453,"try_again_in":86399.999999354}
App/Admin Dashboard Caddy | {"level":"info","ts":1730770807.7506342,"logger":"tls","msg":"finished cleaning storage units"}
App/Admin Dashboard Caddy | {"level":"error","ts":1730770808.4875088,"logger":"http.log.error","msg":"dial tcp [::1]:8080: connect: connection refused","request":{"remote_ip":"::1","remote_port":"38614","client_ip":"::1","proto":"HTTP/1.1","method":"HEAD","host":"localhost:3170","uri":"/ping","headers":{"User-Agent":["curl/8.9.1"],"Accept":["*/*"]}},"duration":0.001032241,"status":502,"err_id":"9x0nt65fn","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
```
3.web view:
![image](https://github.com/user-attachments/assets/af7915bb-1967-415d-b291-910e70b63087)

### Environment

Production

### Version

Cloud
