### ISSUE TITLE
[bug]: Couldn't connect to ws end-point

### ISSUE THREAD

**Issue by DrjavaB** [hoppscotch/hoppscotch#4681]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I just run hopscotch image via docker and make a reverse-proxy with nginx 
proxy_pass http://127.0.0.1:3000/;
proxy_pass http://127.0.0.1:3170/;

domain has SSL certificate and when I launch the app this error appear

```
Mixed Content: The page at 'https://my-domain.com/realtime/websocket' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://my-domain.com/graphql'. This request has been blocked; this endpoint must be available over WSS.
```

![Image](https://github.com/user-attachments/assets/2c1f3f3f-f378-4f13-9c9d-8d139bb478d7)

### Steps to reproduce

the `docker-compose.yml` file I ran

```# To make it easier to self-host, we have a preset docker compose config that also
# has a container with a Postgres instance running.
# You can tweak around this file to match your instances

services:
  # This service runs the backend app in the port 3170
  hoppscotch-backend:
    container_name: hoppscotch-backend
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: backend
    env_file:
      - ./.env
    restart: always
    environment:
      # Edit the below line to match your PostgresDB URL if you have an outside DB (make sure to update the .env file as well)
      - PORT=8080
    volumes:
      # Uncomment the line below when modifying code. Only applicable when using the "dev" target.
      # - ./packages/hoppscotch-backend/:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3180:80"
      - "3170:3170"

  # The main hoppscotch app. This will be hosted at port 3000
  # NOTE: To do TLS or play around with how the app is hosted, you can look into the Caddyfile for
  #       the SH admin dashboard server at packages/hoppscotch-selfhost-web/Caddyfile
  hoppscotch-app:
    container_name: hoppscotch-app
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: app
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3080:80"
      - "3000:3000"

  # The Self Host dashboard for managing the app. This will be hosted at port 3100
  # NOTE: To do TLS or play around with how the app is hosted, you can look into the Caddyfile for
  #       the SH admin dashboard server at packages/hoppscotch-sh-admin/Caddyfile
  hoppscotch-sh-admin:
    container_name: hoppscotch-sh-admin
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: sh_admin
    env_file:
      - ./.env
    depends_on:
      - hoppscotch-backend
    ports:
      - "3280:80"
      - "3100:3100"

  # The preset DB service, you can delete/comment the below lines if
  # you are using an external postgres instance
  # This will be exposed at port 5432
  hoppscotch-db:
    image: postgres:17
    user: postgres
    environment:
      # The default user defined by the docker image
      POSTGRES_USER: postgres
      # NOTE: Please UPDATE THIS PASSWORD!
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
```

### Environment

Production

### Version

Self-hosted

**Comment by mirarifhasan** [comment]
Please check if `VITE_BACKEND_WS_URL` in your `.env` file is set to `wss`.

**Comment by DrjavaB** [comment]
@mirarifhasan 

the error message changed but still can't connect to socket server
![Image](https://github.com/user-attachments/assets/3d38c26d-a535-4f27-ada7-f72f0fef557f)

**Comment by roopepaajanen** [comment]
Did you find a solution to this issue? I am currently facing the same issue with self hosted Hoppscotch 2025.9.1 and 2025.9.2.
The exact error message I recieve in my desktop app is 
WebSocket connection to 'wss://domain-backend.net/graphql' failed: The operation couldn’t be completed. Socket is not connected

**Comment by mirarifhasan** [comment]
@roopepaajanen, could you please confirm if your backend application is currently up and running?
If it is, kindly check the browser’s Network tab to see whether the /graphql requests are successfully communicating with the backend.

Also, could you please share the following .env variables?
```
# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3170/graphql
VITE_BACKEND_WS_URL=ws://localhost:3170/graphql
VITE_BACKEND_API_URL=http://localhost:3170/v1
```

**Comment by roopepaajanen** [comment]
Hi @mirarifhasan, here is the .env variables

In my local Docker setup
```
# Base URLs
VITE_BASE_URL=http://localhost:3000
VITE_SHORTCODE_BASE_URL=http://localhost:3000
VITE_ADMIN_URL=http://localhost:3100

# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3170/graphql
VITE_BACKEND_WS_URL=ws://localhost:3170/graphql
VITE_BACKEND_API_URL=http://localhost:3170/v1
```

In my Kubernetes setup

```    urls:
      base: "https://domain.loadbalancer.net"
      shortcode: "https://domain.loadbalancer.net"
      admin: "https://domain-admin.loadbalancer.net"
      backend:
        gql: "https://domain-backend.loadbalancer.net/graphql"
        ws: "wss://domain-backend.loadbalancer.net/graphql"
        api: "https://domain-backend.loadbalancer.net/v1" 
```

My browser application is running perfectly, the error raises with my desktop application.
In my local Docker instance I notice that the login process returns error 

```
Auth response structure:
"{
  \"error\": \"auth/cookies_not_found\"
}"
```

After refreshing the desktop client the local app works great.

With my application running on kubernetes, the app works for around one minute ( I can login, do any changes etc), until the websocket fails and cuts the connection and returns error 

```
WebSocket connection to 'wss://domain-backend.loadbalancer.net/graphql' failed: The operation couldn’t be completed. Socket is not connected 
```

After recieving the error the desktop app starts to behave in unexpected ways: Changing workspace might not affect the UI,  any modification are not stored etc.

**Comment by roopepaajanen** [comment]
To enhance the context, here is my Istio configs in Kubernetes (Virtualservice & Gateway)
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
spec:
  gateways:
    - hoppscotch-ingress
  hosts:
    - domain.global.load-balancer.net
    - domain-admin.global.load-balancer.net
    - domain-backend.global.load-balancer.net
  http:
    - match:
        - authority:
            exact: domain.global.load-balancer.net
          uri:
            prefix: /proxy
      route:
        - destination:
            host: proxyscotch.hoppscotch.svc.cluster.local
            port:
              number: 9159
    - match:
        - authority:
            exact: domain.global.load-balancer.net
          uri:
            prefix: /desktop-app-server
      route:
        - destination:
            host: hoppscotch-community.hoppscotch.svc.cluster.local
            port:
              number: 3200
    - match:
        - authority:
            exact: domain.global.load-balancer.net
      route:
        - destination:
            host: hoppscotch-community.hoppscotch.svc.cluster.local
            port:
              number: 3000
    - match:
        - authority:
            exact: domain-admin.global.load-balancer.net
      route:
        - destination:
            host: hoppscotch-community.hoppscotch.svc.cluster.local
            port:
              number: 3100
    - match:
        - authority:
            exact: domain-backend.global.load-balancer.net
          headers:
            upgrade:
              exact: websocket
          uri:
            prefix: /graphql
      route:
        - destination:
            host: hoppscotch-community.hoppscotch.svc.cluster.local
            port:
              number: 3170
      timeout: 24h
    - corsPolicy:
        allowCredentials: true
        allowHeaders:
          - Authorization
          - Content-Type
          - X-Requested-With
          - apollo-require-preflight
          - Sec-WebSocket-Protocol
          - Sec-WebSocket-Key
          - Sec-WebSocket-Version
          - Connection
          - Upgrade
        allowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        allowOrigins:
          - exact: domain.global.load-balancer.net
          - exact: domain-admin.global.load-balancer.net
          - exact: app://domain_loadbalancer_net
          - exact: http://app.domain_loadbalancer_net
        exposeHeaders:
          - Content-Length
          - Content-Type
        maxAge: 24h
      match:
        - authority:
            exact: domain-backend.global.load-balancer.net
      route:
        - destination:
            host: hoppscotch-community.hoppscotch.svc.cluster.local
            port:
              number: 3170
```
And Gateway

```
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: hoppscotch-Gateway
  namespace: hoppscotch
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - domain.loadbalancer.net
        - domain-admin.loadbalancer.net
        - domain-backend.loadbalancer.net
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - domain.loadbalancer.net
        - domain-admin.loadbalancer.net
        - domain-backend.loadbalancer.net
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: global-lb-wildcard
        mode: SIMPLE
    - hosts:
        - domain-backend.loadbalancer.net
      port:
        name: wss
        number: 443
        protocol: HTTPS
      tls:
        credentialName: global-lb-wildcard
        mode: SIMPLE

```

**Comment by esotericman** [comment]
I have the same error, Any solutions? I use AIO docker container, as this error rises, hoppscotch log 
`Backend Server | ::1 GET /graphql 400 - 0.383 ms`

**Comment by esotericman** [comment]
I found the cause, I used nginx reverse proxy, after added

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

It works now.

**Comment by andresanches** [comment]
For those of us using NGINX-ingress (F5's version, not the opensource one) the fix is to add this annotation to the Ingress object ([source](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#:~:text=nginx.org/websocket%2Dservices)):

```yaml
nginx.org/websocket-services: "<<your k8s service name here>>"
```

Full example:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch
  labels:
    app: hoppscotch
  annotations:
    external-dns.alpha.kubernetes.io/hostname: **redacted***
    hostname: **redacted**
    nginx.org/websocket-services: "hoppscotch"  # This is what enables websockets
spec:
  rules:
    - host: **redacted**
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hoppscotch
                port:
                  number: 80
```
