### ISSUE TITLE
[bug]: Frontend GraphQL and Backend API calls not using .env URL values

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [hoppscotch/hoppscotch#4700]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I have configured my Hoppscotsch environment to use the AIO (all-in-one) approach. I have used docker compose to start Hoppscotsch and a local Postgres DB. 

My `HOPP_AIO_ALTERNATE_PORT=80` and my docker compose is forwarding everything from port `80` to `3000` in my local environment (referenced below).

The `.env` file frontend config has been updated to use the AIO sub-path approach. Even though I have updated `VITE_BACKEND_GQL_URL` and `VITE_BACKEND_API_URL` values it looks like the frontend is still using the default `localhost:3170` URL (see screenshot below for network calls to fetch graphql data on load as well as the logout operation).

Is there something I'm missing?

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/4f227ae5-8dfd-4e86-a97b-b05100bf6a39" />

```.env
# .env 

#-----------------------Frontend Config------------------------------#

# Base URLs
VITE_BASE_URL=http://localhost:3000
VITE_SHORTCODE_BASE_URL=http://localhost:3000
VITE_ADMIN_URL=http://localhost:3000/admin

# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3000/backend/graphql
VITE_BACKEND_WS_URL=wss://localhost:3000/backend/graphql
VITE_BACKEND_API_URL=http://localhost:3000/backend/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

# Set to `true` for subpath based access
ENABLE_SUBPATH_BASED_ACCESS=true
```

```yml
# docker-compose.yml

services:
  hoppscotch:
    container_name: HOPPSCOTCH
    image: hoppscotch/hoppscotch:latest
    ports:
      - "3000:80"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    container_name: POSTGRES_HS
    image: public.ecr.aws/docker/library/postgres:15.5-alpine
    ports:
      - "5432:5432"
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - hoppscotchData:/var/lib/postgresql/data

volumes:
  hoppscotchData:

```

### Steps to reproduce

provided above.

### Environment

Production

### Version

Local
