### ISSUE TITLE
[bug]: `pnpm dev` results in Code 139

### ISSUE THREAD

**Issue by yousefmarey12** [hoppscotch/hoppscotch#4745]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

I want to start a development server on Hoppscotch, and I couldn't do so because I did not have enough RAM. However, after I extended my RAM to 24 GB (for other reasons), `pnpm i` worked successfully. However, `pnpm dev` gives me the following error:

```txt
│ [dev:gql-codegen] Segmentation fault (core dumped)
│ [dev:gql-codegen]  ELIFECYCLE  Command failed with exit code 139.
│ [dev:vite       ]  ELIFECYCLE  Command failed.
│ ERROR: "dev:gql-codegen" exited with 139.
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 4.9s at /home/yousefmarey12/web_dev/hoppscotch/packages/hoppscotch-selfhost-web
/home/yousefmarey12/web_dev/hoppscotch/packages/hoppscotch-selfhost-web:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @hoppscotch/selfhost-web@2025.1.1 do-dev: `pnpm run dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

The problem is with the `gql-codegen` and here is all the information that I can give you:

`hoppscotch-selfhost-web/gql-codegen.yml`:

```yml
overwrite: true
schema: "../../gql-gen/*.gql"
generates:
  src/api/generated/graphql.ts:
    documents: "src/**/*.graphql"
    plugins:
      - add:
          content: >
            /* eslint-disable */
            // Auto-generated file (DO NOT EDIT!!!), refer gql-codegen.yml
      - typescript
      - typescript-operations
      - typed-document-node
      - typescript-urql-graphcache

  src/api/generated/backend-schema.json:
    plugins:
      - urql-introspection
```

I understand that a code of 139 means memory that shouldn't be accessed had tried to be accessed, but I couldn't figure out where the problem is as I don't really work with codegen or graphql that much.

For reference, I followed [this tutorial](https://github.com/hoppscotch/hoppscotch/issues/4145#issuecomment-2209375118) to set up a development server.

I am using WSL 2 (Ubuntu). 

### Steps to reproduce

Follow the steps on the tutorial while using WSL Ubuntu.

### Environment

Production

### Version

Self-hosted
