### ISSUE TITLE
[bug]: Desktop App not being able to load already existing workspaces and requests from self hosted instance

### ISSUE THREAD

**Issue by LordSimal** [hoppscotch/hoppscotch#4812]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

We just recently updated to the newly released [2025.2.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2025.2.0) which added support for connecting the desktop app to the self-hosted instance.

We have checked out the newest tag in the repo, recreated the containers with the newest image and the webinterface works fine.

But after logging in via the App it doesn't
- load the already existing workspaces
- load the already existing requests in the personal workspace
- save newly created requests in the personal workspace

I just see a loading animation in the workspace tab

![Image](https://github.com/user-attachments/assets/81ddb9c7-c36f-4c3b-a0f3-38f5f73ef60e)

### Steps to reproduce

1. Update to 2025.2.0
2. Adjust docker-compose.yml to also expose Port 3200
3. Download the latest app build from https://hoppscotch.com/download and install it (I am on MacOS)
4. Connect to the self hosted instance like it is explained [here](https://github.com/hoppscotch/hoppscotch/issues/3523#issuecomment-2697279791)
5. Login works as expected, but no requests or workspaces are loaded or saved properly.

----

To explain our setup a bit:
We have checked out the repo, specifically checkout out the current latest tag, and adjusted the `.env` and `docker-compose.yml` to use the AIO variant.

Here is our docker-compose.yml (which I have cleaned up from all unnecessary services)
```
root@scarecrow:~/hoppscotch# cat docker-compose.yml 
# To make it easier to self-host, we have a preset docker compose config that also
# has a container with a Postgres instance running.
# You can tweak around this file to match your instances

services:
 # The service that spins up all 3 services at once in one container
  hoppscotch-aio:
    container_name: hoppscotch-aio
    restart: unless-stopped
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: aio
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"
      - "3200:3200"
      - "3080:80"

  # The preset DB service, you can delete/comment the below lines if
  # you are using an external postgres instance
  # This will be exposed at port 5432
  hoppscotch-db:
    image: postgres:15
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      # The default user defined by the docker image
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: x3WTvGaKCdhZJwExMr10nC0tDLxer8Fq
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
```

and a NGINX Config to map the internal Ports to publicly available Domains
- api-docs.mydomain.com => Port 3000
- api-docs-admin.mydomain.com => Port 3100
- api-docs-backend.mydomain.com => Port 3170
- api-docs-app.mydomain.com => Port 3200

### Environment

Release

### Version

Self-hosted
