### ISSUE TITLE
[bug]: Deskop-App: cannot connecto to own instance - "Verification error: Key validation failed: HTTP request failed: error decoding response body"

### ISSUE THREAD

**Issue by schroedermatthias** [hoppscotch/hoppscotch#4831]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Situation / Configuration:
- Desktop App Version: 25.2.0 (20250304.072649)
- Backend Version: 2025.2.0
- Backend Orchestrator: Kubernetes
- Single containers (frontend, backend, admin)

I’m unable to use the new feature to connect my own instance. The error message states:

**“Verification error: Key validation failed: HTTP request failed: error decoding response body”**

Due to a lack of documentation, I configured my Ingress so that the path `/desktop-app-server/` implicitly points to the frontend container (see `ingress.yaml` below). However, the server responds with HTML and I guess my client expects JSON. It is very frustrating to guess / reverse engineer the internal routing configuration the AIO image does.

<img width="449" alt="Image" src="https://github.com/user-attachments/assets/92869492-e910-4a79-a8d9-4b31e90280b4" />

Relevant Configuration Settings:

```env
WHITELISTED_ORIGINS=https://hoppscotch.redacted.de,app://hoppscotch_redacted_de
ENABLE_SUBPATH_BASED_ACCESS=true
```

My kubernetes ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoppscotch
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hoppscotch.redacted.de
      secretName: hoppscotch.redacted.de
  rules:
    - host: hoppscotch.redacted.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-frontend
                port:
                  number: 80
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-backend
                port:
                  number: 80
          - path: /v1/
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-backend
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: hoppscotch-admin
                port:
                  number: 80


```

In general I think that a project like this should be though cloud-native from the beginning with proper documentation about a Kubernetes deployment. I think having 3 images seperating concerns is already a good approach, an AIO container image with all processes inside one container is not.

I think this project which I really like would hughely profit from a Helm chart to ease deployments in the cloud.

Best,
Matthias

### Steps to reproduce

Operate hoppscotch in Kubernetes ;-)

### Environment

Production

### Version

Self-Hosted

**Comment by liyasthomas** [comment]
Hi @schroedermatthias can you checked out our [helm-charts](https://github.com/hoppscotch/helm-charts) repo?

**Comment by schroedermatthias** [comment]
@liyasthomas thanks for pointing me to the Helm Chart. As I can see, it's pretty new, the last time I checked it did not exist :)

**Comment by schroedermatthias** [comment]
> Here are few more pointers to help you:
> 
>     * Have you enabled [subpath based access](https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#subpath-based-access)?
> 
>     * Have you updated the [`WHITELISTED_ORIGINS`](https://docs.hoppscotch.io/documentation/clients/desktop#hoppscotch-self-hosted-edition-for-community) environment variables?

Yes, please see my initial post under "Relevant Configuration Settings:"

**Comment by CuriousCorrelation** [comment]
Hi @schroedermatthias, thanks for the report, to dive a bit deeper into the implementation details, essentially the [prod.Dockerfile](https://github.com/hoppscotch/hoppscotch/blob/main/prod.Dockerfile) exposes port `3200` for [webapp-server](https://github.com/hoppscotch/hoppscotch/blob/22c341896dcc8cbf361bb2c85ea4ffd08d461106/prod.Dockerfile#L171-L180) - this is the server that the new Desktop App uses to fetch the Hoppscotch (web)app contents (and not the frontend server itself, see also [docker-compose.yml](https://github.com/hoppscotch/hoppscotch/blob/22c341896dcc8cbf361bb2c85ea4ffd08d461106/docker-compose.yml#L94-L105), and the same mentioned in [AIO](https://github.com/hoppscotch/hoppscotch/blob/22c341896dcc8cbf361bb2c85ea4ffd08d461106/docker-compose.yml#L125)), which is then [proxied by Caddy](https://github.com/hoppscotch/hoppscotch/blob/22c341896dcc8cbf361bb2c85ea4ffd08d461106/aio-subpath-access.Caddyfile#L24-L27) for subpath access (as oppose to [multiport](https://github.com/hoppscotch/hoppscotch/blob/main/aio-multiport-setup.Caddyfile)). Perhaps making sure the correct server is exposed might resolve your issue.

**Comment by CuriousCorrelation** [comment]
Hi @schroedermatthias, the `webapp-server` is not part of the frontend image - it's a completely separate component and is not available as a separate published image at this moment

**Comment by schroedermatthias** [comment]
Hi @CuriousCorrelation Thanks. This actually means, that the newly introduced feature to use a self-hosted backend breaks with the approach to use individual containers outlined here: https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#using-individual-containers-for-the-services-2.

Maybe this information should be added in the docs?

Are there plans to ship an image for the `webapp-server`? Now I have to use the "fat" image which is not cloud native :-(

Thanks,
Matthias

**Comment by MC-intel** [comment]
It looks like the issue might be caused by the `/desktop-app-server/` path pointing to the frontend instead of the backend. Try updating your Kubernetes Ingress configuration to explicitly route `/desktop-app-server/` to `hoppscotch-backend`. Here’s an example:

```yaml
- path: /desktop-app-server/
  pathType: Prefix
  backend:
    service:
      name: hoppscotch-backend
      port:
        number: 80
```

This should ensure that requests to the desktop app server reach the correct backend service instead of returning HTML when JSON is expected. Let us know if this helps!

**Comment by brunnobb** [comment]
`/desktop-app-server/` should not be backend or frontend.

i have made it run with and additional container at my compose file



 ```
 hoppscotch-app:
    image: hoppscotch/hoppscotch:latest
    container_name: hoppscotch-app
    restart: unless-stopped    
    environment:
      ...
      - ENABLE_SUBPATH_BASED_ACCESS=false
    ports:
      - "3200:3200" # Hoppscotch default port for web access for the app
    depends_on:      
      - hoppscotch-backend
      - hoppscotch-admin
      - hoppscotch-frontend

```


I do use separate containers for backend, frontend, admin, etc..
So this were created at my reverse proxy as hoppscotch-app.myinstance.com

THEN 

you need to add the records to  WHITELISTED_ORIGINS
could be excessive, but i have had a few cors issues (check debugger on local instance.. (just F12)

WHITELISTED_ORIGINS=https://hoppscotch-backend.myinstance.com,https://hoppscotch.myinstance.com,https://hoppscotch-admin.myinstance.com,app://hoppscotch_myinstance_com,http://app.hoppscotch_app_myinstance_com,app://app.hoppscotch_myinstance_com


and on the local hoopscotch.. i needed to use 
`hoppscotch-app.myinstance.com`
as URL



@liyasthomas is there a way to run only the app server using the default AIO container?
it is running everything, but only app is mapped.
