### ISSUE TITLE
[bug]: Deploy with Helm charts hoppscotch with image: hoppscotch/hoppscotch and tag 2025.2.3

### ISSUE THREAD

**Issue by oo00spy00oo** [hoppscotch/hoppscotch#4938]
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Current behavior

I've tried with these configuration when install with Helm charts with image: hoppscotch/hoppscotch and tag 2025.2.3. When the application are deployed, I cannot access the application via domain, I also try to forward traffic from Kubernetes server to my local machine but have no available server to access. The deployment logs looks fine:

<img width="1026" alt="Image" src="https://github.com/user-attachments/assets/648904c9-f6ec-4052-b90c-e843147d15f7" />

### Steps to reproduce

Solution 1: with subpath diable:

```yaml
community:
  replicas: 1
  image:
    repository: hoppscotch/hoppscotch
    tag: 2025.2.3
    pullPolicy: IfNotPresent
  migration:
    upgradeEnabled: true
  config:
    database:
      external: true
      url: "<REDACTED>"
    rateLimit:
      ttl: 60
      max: 100
    authjwt:
      sessionSecret: "<REDACTED>"
      jwtSecret: "<REDACTED>"
    auth:
      allowedProviders: "GITHUB"
      github:
        clientId: "<REDACTED>"
        clientSecret: "<REDACTED>"
        callbackUrl: "http://hoppscotch-backend.example.com/v1/auth/github/callback"
        scope: "user:email"
    community:
      enableSubpathBasedAccess: false
    urls:
      base: "https://hoppscotch.example.com"
      shortcode: "https://hoppscotch.example.com"
      admin: "https://hoppscotch-admin.example.com"
      backend:
        gql: "https://hoppscotch-backend.example.com/graphql"
        ws: "wss://hoppscotch-backend.example.com/graphql"
        api: "http://hoppscotch-backend.example.com/v1"
      redirect: "https://hoppscotch.example.com"
      whitelistedOrigins: "https://hoppscotch-backend.example.com,https://hoppscotch.example.com,https://hoppscotch-admin.example.com,http://hoppscotch-backend.example.com,http://hoppscotch.example.com,http://hoppscotch-admin.example.com"
service:
  ingress:
    enabled: true
    className: traefik
    mainHost: hoppscotch.example.com
    adminHost: hoppscotch-admin.example.com
    backendHost: hoppscotch-backend.example.com
```

Solution 2: With subpath enable
```yaml
community:
  replicas: 1
  image:
    repository: hoppscotch/hoppscotch
    tag: 2025.2.3
    pullPolicy: IfNotPresent
  migration:
    upgradeEnabled: true
  config:
    database:
      external: true
      url: "<REDACTED>"
    rateLimit:
      ttl: 60
      max: 100
    authjwt:
      sessionSecret: "<REDACTED>"
      jwtSecret: "<REDACTED>"
    auth:
      allowedProviders: "GITHUB"
      github:
        clientId: "<REDACTED>"
        clientSecret: "<REDACTED>"
        callbackUrl: "http://hoppscotch.example.com/backend/v1/auth/github/callback"
        scope: "user:email"
    community:
      enableSubpathBasedAccess: true
    urls:
      base: "https://hoppscotch.example.com"
      shortcode: "https://hoppscotch.example.com"
      admin: "https://hoppscotch.example.com/admin"
      backend:
        gql: "https://hoppscotch.example.com/backend/graphql"
        ws: "wss://hoppscotch.example.com/backend/graphql"
        api: "http://hoppscotch.example.com/backend/v1"
      redirect: "https://hoppscotch.example.com"
      whitelistedOrigins: "https://hoppscotch.example.com,https://hoppscotch.example.com/admin,https://hoppscotch.example.com/graphql"
service:
  ingress:
    enabled: true
    className: traefik
    mainHost: hoppscotch.example.com
    adminHost: hoppscotch.example.com/admin
    backendHost: hoppscotch.example.com/backend
```

### Logs and Screenshots

```shell

```

### Environment

Production

### Hoppscotch Version

Self-hosted

### Interceptor

Not Applicable - Issue not related to network requests

### Operating System

None

**Comment by oo00spy00oo** [comment]
> @oo00spy00oo
> 
> To access you have to add your domain name.
> 
> Replace,
> hoppscotch.example.com with **hoppscotch.yourdomainname.com**
> hoppscotch-admin.example.com with **hoppscotch-admin.yourdomainname.com**
> hoppscotch-backend.example.com with **hoppscotch-backend.yourdomainname.com**
> 
> To attach the IP address to your domain.
> `kubectl get ingress ` (this command will provide the IP address of you cluster)

I know that, guy

I replaced my real domain by example.com

**Comment by oo00spy00oo** [comment]
> [@oo00spy00oo](https://github.com/oo00spy00oo)
> 
> I was able to replicate your problem on my end. When using the **traefik**
> 
> After some troubleshooting, I’ve resolved the issue where the Hoppscotch application couldn’t be accessed via the domain when using Traefik as the Ingress Controller. The root cause was that Traefik wasn’t installed in the cluster, which meant there was no Ingress Controller to route external traffic to the hoppscotch-community service
> 
> * Ran `kubectl get pods -n traefik `and `kubectl get svc -n traefik`, both returned "No resources found in traefik namespace," confirming Traefik wasn’t deployed.
> * Confirmed the Hoppscotch app was running fine internally (hoppscotch-community-5c5cfdd6c6-lwfpx pod was Running and service hoppscotch-community was up with ClusterIP), but it wasn’t accessible externally without an Ingress Controller.
> 
> Installed Traefik Used Helm to install Traefik, which is a clean and manageable approach:
> 
> ```
> helm repo add traefik https://helm.traefik.io/traefik
> helm repo update
> helm install traefik traefik/traefik --namespace traefik --create-namespace
> ```
> 
> Verified Traefik deployment:
> 
> ```
> kubectl get pods -n traefik
> kubectl get svc -n traefik
> ```
> 
> This showed a Traefik pod running and a LoadBalancer service with an EXTERNAL-IP (e.g., 203.0.113.10), indicating Traefik was now exposed externally.
> 
> **Note**: Remove this line(kubernetes.io/ingress.class: nginx) from ingress.yaml file. If you are using traefik.

@g3Bg2  Many thanks, but this is not the main point of this issue.

After reviewing the whole helm charts source, I found this:

```yaml
# Service configuration
service:
  apiVersion: v1
  name: hoppscotch-community
  app: hoppscotch-community
```

It meant in the helm chart the name is fixed with `hoppscotch-community`.

Solution 1: The install command must change from `helm install community-hoppscotch ./charts/shc -f values.yaml -n hoppscotch` to `helm install hoppscotch ./charts/shc -f values.yaml -n hoppscotch`

Solution 2: If you are installing with the name differrent from `hoppscotch` (eg: community-hoppscotch), you must change the section `service` in `values.yaml` with format: `$releaseName-community`.

Eg:
```yaml
service:
  name: community-hoppscotch-community
  app: community-hoppscotch-community
```
