### ISSUE TITLE
[bug]: Self hosted helm deploy for hoppscotch fails with "nodemailer transport configuration object"

### ISSUE THREAD

**Issue by tdevarajan** [hoppscotch/hoppscotch#5028]
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Current behavior

I successfully installed the Hoppscotch monolithic setup on my AWS cloud, and it ran smoothly for about a day. However, after configuring the mailer this morning, the backend started failing with the following error.

``` Backend Server | [Nest] 23  - 04/29/2025, 3:13:45 AM   ERROR [ExceptionHandler] Make sure to provide a nodemailer transport configuration object, connection url or a transport plugin instance.
Backend Server | Error: Make sure to provide a nodemailer transport configuration object, connection url or a transport plugin instance.
Backend Server |     at MailerService.validateTransportOptions (/dist/backend/node_modules/.pnpm/@nestjs-modules+mailer@2.0.2_@nestjs+common@10.4.4_class-transformer@0.5.1_class-valida_280615842527df026e7c134e32758d6c/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:64:19)
Backend Server |     at new MailerService (/dist/backend/node_modules/.pnpm/@nestjs-modules+mailer@2.0.2_@nestjs+common@10.4.4_class-transformer@0.5.1_class-valida_280615842527df026e7c134e32758d6c/node_modules/@nestjs-modules/mailer/dist/mailer.service.js:49:14)
Backend Server |     at Injector.instantiateClass (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/injector.js:365:19)
Backend Server |     at callback (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/injector.js:65:45)
Backend Server |     at async Injector.resolveConstructorParams (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/injector.js:144:24)
Backend Server |     at async Injector.loadInstance (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/injector.js:70:13)
Backend Server |     at async Injector.loadProvider (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/injector.js:97:9)
Backend Server |     at async /dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/instance-loader.js:56:13
Backend Server |     at async Promise.all (index 4)
Backend Server |     at async InstanceLoader.createInstancesOfProviders (/dist/backend/node_modules/.pnpm/@nestjs+core@10.4.4_@nestjs+common@10.4.4_class-transformer@0.5.1_class-validator@0.14._888121cfb1202a7b428592c174f49f51/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
Exiting process because Backend Server exited with code null
``` 

Here is my configMap 

```
apiVersion: v1
data:
  ACCESS_TOKEN_VALIDITY: 1d
  ALLOW_SECURE_COOKIES: "true"
  DATA_ENCRYPTION_KEY: data encryption key with 32 char
  DATABASE_URL: postgresql://hoppscotch:changeme@hoppscotchdb:5432/hoppscotch?sslmode=require
  ENABLE_SUBPATH_BASED_ACCESS: "false"
  GITHUB_CALLBACK_URL: http://backend.example.com/v1/auth/github/callback
  GITHUB_CLIENT_ID: dummyGithubClientId
  GITHUB_CLIENT_SECRET: dummyGithubClientSecret
  GITHUB_SCOPE: user:email
  GOOGLE_CALLBACK_URL: http://backend.example.com/v1/auth/google/callback
  GOOGLE_CLIENT_ID: dummyGoogleClientId
  GOOGLE_CLIENT_SECRET: dummyGoogleClientSecret
  GOOGLE_SCOPE: email,profile
  JWT_SECRET: dummyJwtSecret
  MAGIC_LINK_TOKEN_VALIDITY: "3"
  MAILER_ADDRESS_FROM: noreply@mail.com
  MAILER_SMTP_ENABLE: "true"
  MAILER_SMTP_HOST: email-smtp.us-west-2.amazonaws.com
  MAILER_SMTP_PASSWORD: password
  MAILER_SMTP_PORT: "587"
  MAILER_SMTP_SECURE: "false"
  MAILER_SMTP_URL: smtps://username:password@email-smtp.us-west-2.amazonaws.com
  MAILER_SMTP_USER: username
  MAILER_TLS_REJECT_UNAUTHORIZED: "false"
  MAILER_USE_CUSTOM_CONFIGS: "false"
  MICROSOFT_CALLBACK_URL: http://backend.example.com/v1/auth/microsoft/callback
  MICROSOFT_CLIENT_ID: dummyMicrosoftClientId
  MICROSOFT_CLIENT_SECRET: dummyMicrosoftClientSecret
  MICROSOFT_SCOPE: user.read
  MICROSOFT_TENANT: dummyTenantId
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_TTL: "60"
  REDIRECT_URL: http://frontend.example.com
  REFRESH_TOKEN_VALIDITY: 1d
  SESSION_SECRET: dummySessionSecret
  TOKEN_SALT_COMPLEXITY: "10"
  VITE_ADMIN_URL: http://admin.example.com
  VITE_ALLOWED_AUTH_PROVIDERS: GOOGLE,MICROSOFT,GITHUB,EMAIL
  VITE_APP_PRIVACY_POLICY_LINK: https://docs.example.com/privacy
  VITE_APP_TOS_LINK: https://docs.example.com/terms
  VITE_BACKEND_API_URL: http://backend.example.com/v1
  VITE_BACKEND_GQL_URL: http://backend.example.com/graphql
  VITE_BACKEND_WS_URL: ws://backend.example.com/graphql
  VITE_BASE_URL: http://frontend.example.com
  VITE_SHORTCODE_BASE_URL: http://frontend.example.com
  WHITELISTED_ORIGINS: http://frontend.example.com,http://admin.example.com,http://backend.example.com
kind: ConfigMap 
```

Docker image: hoppscotch/hoppscotch:2025.3.2 

After encountering the error, I attempted a Terraform destroy, deployed the latest image, but still had no success.

Could you help me troubleshoot and resolve the issue?

### Steps to reproduce

1. Helm deploy self hosted monolithic docker image to EKS cluster 
2. Deploy with default mailer settings in the values.yaml 
3. Try updating the values.yaml with mailer settings as defined in the ConfigMap

The backend failing to start with the error mentioned about and doesn't recover. 

### Logs and Screenshots

```shell

```

### Environment

Production

### Hoppscotch Version

Self-hosted

### Interceptor

Not Applicable - Issue not related to network requests

### Operating System

Linux
