### ISSUE TITLE
[bug]: With the Hoppscotch CLI, it can now only read JSON.

### ISSUE THREAD

**Issue by rintaaaa** [hoppscotch/hoppscotch#5166]
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Current behavior

cli version
```
hopp -v
0.23.2
```
error message
```
 hopp test <collectionID>  --token  <access token> --server <server-url>
INVALID_FILE_TYPE Please provide file of extension type .json: <collectionID>
```
Execution with a collection ID is no longer supported, and only JSON is accepted. Why is this?

### Steps to reproduce

- docker compose
```
services:
  hoppscotch-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hoppscotch-cli
    volumes:
      - ./logs:/workspace/logs:rw
      - ./json:/workspace/json:ro
      - ./cron/root:/etc/cron.d/root:ro
    networks:
      - hoppscotch-cli

networks:
  hoppscotch-cli:
    name: hoppscotch-cli
    driver: bridge
```

- Dockerfile
```
FROM amazonlinux:2023

RUN dnf update -y && dnf install -y \
    python3 \
    make \
    gcc-c++ \
    cronie \
    procps \
    zlib-devel \
    libuv-devel \
    brotli-devel \
    c-ares-devel \
    nghttp2 \
    openssl-devel \
    libicu-devel \
    tzdata \
    && dnf clean all

RUN curl -fsSL https://rpm.nodesource.com/setup_20.x | bash - \
    && dnf install -y nodejs \
    && dnf clean all

RUN npm install -g @hoppscotch/cli

WORKDIR /workspace

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

- entrypoint.sh

```
#!/bin/bash
crontab /etc/cron.d/root

exec crond -n 
```

### Logs and Screenshots

```shell

```

### Environment

Production

### Hoppscotch Version

Local

### Interceptor

Not Applicable - Issue not related to network requests

### Operating System

Linux
