### ISSUE TITLE
[bug]: Can't login to my self-hosted deployment from desktop app

### ISSUE THREAD

**Issue by m-adawi** [hoppscotch/hoppscotch#5186]
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Platform

Desktop App

### Browser

Firefox

### Operating System

Windows

### Bug Description

I'm self-hosting Hoppscotch and using Google OAuth for login, it's secured with SSL. everything in the browser is working fine, but when I try to login from desktop keeps loading forever:
![Image](https://github.com/user-attachments/assets/8a8aee6f-5f3b-4ab1-b2be-cbb28ffba130)

I also find this error in the console logs of the desktop app:
```
Auth response structure: {
  "error": "auth/cookies_not_found"
}
```
![Image](https://github.com/user-attachments/assets/ea3aa6be-5e64-411f-848c-5280c7fa6c84)

My .env file:
```bash
HOPPSCOTCH_HOST=hoppscotch.mydomain.com
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://XXXXXXXXX:XXXXXXXXX@hoppscotch-db:5432/hoppscotch

# Auth Tokens Config
JWT_SECRET="XXXXXXXXXX"
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY= 3
# Default validity is 7 days (604800000 ms) in ms
REFRESH_TOKEN_VALIDITY="604800000"
# Default validity is 1 day (86400000 ms) in ms
ACCESS_TOKEN_VALIDITY="86400000"
SESSION_SECRET='XXXXXXXXXXXXXXXXXXXXXXXXX'
# Reccomended to be true, set to false if you are using http
# Note: Some auth providers may not support http requests
ALLOW_SECURE_COOKIES=true

# Sensitive Data Encryption Key while storing in Database (32 character)
DATA_ENCRYPTION_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Hoppscotch App Domain Config
REDIRECT_URL="https://$HOPPSCOTCH_HOST"
# Whitelisted origins for the Hoppscotch App.
# This list controls which origins can interact with the app through cross-origin comms.
# - localhost ports (3170, 3000, 3100): app, backend, development servers and services
# - app://localhost_3200: Bundle server origin identifier
#   NOTE: `3200` here refers to the bundle server (port 3200) that provides the bundles,
#   NOT where the app runs. The app itself uses the `app://` protocol with dynamic
#   bundle names like `app://{bundle-name}/`
WHITELISTED_ORIGINS="http://localhost:3170,http://localhost:3000,http://localhost:3100,app://localhost_3200,app://hoppscotch,http://$HOPPSCOTCH_HOST,app://hoppscotch_mydomain_com,app://hoppscotch_mydomain_com_3200,http://app.hoppscotch_mydomain_com,http://app.hoppscotch_mydomain_com_3200"
VITE_ALLOWED_AUTH_PROVIDERS=GOOGLE

# Google Auth Config
GOOGLE_CLIENT_ID="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
GOOGLE_CLIENT_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
GOOGLE_CALLBACK_URL="https://$HOPPSCOTCH_HOST/backend/v1/auth/google/callback"
GOOGLE_SCOPE="email,profile"

# Mailer config
MAILER_SMTP_ENABLE="true"
MAILER_USE_CUSTOM_CONFIGS="false"
MAILER_ADDRESS_FROM='"mydomain" <hoppscotch@mydomain.com>'

MAILER_SMTP_URL="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx" # used if custom mailer configs is false

# Rate Limit Config
RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP


#-----------------------Frontend Config------------------------------#


# Base URLs
VITE_BASE_URL=https://$HOPPSCOTCH_HOST
VITE_SHORTCODE_BASE_URL=https://$HOPPSCOTCH_HOST
VITE_ADMIN_URL=https://$HOPPSCOTCH_HOST

# Backend URLs
VITE_BACKEND_GQL_URL=https://$HOPPSCOTCH_HOST/backend/graphql
VITE_BACKEND_WS_URL=ws://$HOPPSCOTCH_HOST/backend/graphql
VITE_BACKEND_API_URL=https://$HOPPSCOTCH_HOST/backend/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

# Set default to null as https://proxy.hoppscotch.io/ doesn't require an access token
VITE_PROXYSCOTCH_ACCESS_TOKEN=

# Set to `true` for subpath based access
ENABLE_SUBPATH_BASED_ACCESS=true

```

My docker-compose file (I'm using Traefik as a reverse proxy):
```yaml
services:
  hoppscotch-aio:
    container_name: hoppscotch-aio
    image: hoppscotch/hoppscotch:2025.5.3
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"
      - "3200:3200"
      - "3080:80"
    networks:
      - network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoppscotch.rule=Host(`hoppscotch.mydomain.com`)"
      - "traefik.http.routers.hoppscotch.entrypoints=websecure"
      - "traefik.http.routers.hoppscotch.service=hoppscotch"
      - "traefik.http.services.hoppscotch.loadbalancer.server.port=80"
      - "traefik.http.routers.hoppscotch-desktop.rule=Host(`hoppscotch.mydomain.com`) && PathPrefix(`/desktop-app-server`)"
      - "traefik.http.routers.hoppscotch-desktop.entrypoints=websecure"
      - "traefik.http.routers.hoppscotch-desktop.service=hoppscotch-desktop"
      - "traefik.http.services.hoppscotch-desktop.loadbalancer.server.port=3200"

  hoppscotch-migrate:
    build:
      dockerfile: prod.Dockerfile
      context: .
      target: backend
    env_file:
      - ./.env
    networks:
      - network
    depends_on:
      hoppscotch-db:
        condition: service_healthy
    command: sh -c "pnpx prisma migrate deploy"

  hoppscotch-db:
    image: postgres:15
    user: postgres
    networks:
      - network
    environment:
      POSTGRES_USER: XXXXXXXXXXX
      POSTGRES_PASSWORD: XXXXXXXXX
      POSTGRES_DB: hoppscotch
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  network:
    external: true

```

## Steps to reproduce
1. I add our own self-hosted instance to the desktop app 
2. It loads it fine
3. I press the login button
4. It opens the browser and I'm asked to login using google
5. I login
6. I get the message: "Login Complete you have logged in to the desktop app. You can close this browser window", 
7. I open the desktop app I find the login screen loading with that spinning gear and it keeps loading forever, when I check the console logs I find this in the info logs:
```
index-CnTfQrJ9.js:2738 Auth response structure: {
  "error": "auth/cookies_not_found"
}
```

### Deployment Type

Self-hosted (on-prem deployment)

### Version

2025.5.3
